- lib/net/imap.rb
> Set timeout for IDLE responses

- .github/workflows/test.yml
See https://github.com/actions/runner/issues/849 for details about the issue.
> CI: Quote "3.0" in matrix

- net-imap.gemspec
https://github.com/rubygems/rubygems/issues/5255
> Don't install bin directory

- lib/net/imap/response_parser.rb
- lib/net/imap/response_parser/parser_utils.rb
This is especially helpful when making big changes to the parser. :)
> 🔎 Improve parse error debugging

- lib/net/imap/data_encoding.rb
- test/net/imap/test_imap_data_encoding.rb
Reported by svalkanov in <https://hackerone.com/reports/1969040>.
> Decode UTF-7 more strictly

- test/net/imap/test_imap.rb
Several tests are still using `imaps_test`, which didn't have a timeout to protect against failing tests.  They may or may not be converted to `with_fake_server` later, but adding a timeout is sufficient for now.
> ⏱️ Add Timeout to several existing SSL tests

- lib/net/imap/response_parser.rb
Many of the methods called by `response-data` are renamed (or given an alias) according to the new naming conventions:
* Match the ABNF name where possible (converting to lowercase and `-` to `_`)
* Uses double-underscore (`__`) to signify when a method only match part of an ABNF production (or more than a single ABNF production).
Aditionally, the `response-cond-*` methods were split and rewritten to more closely match the ABNF.  Extra assertions have been added, even though they are redundant with the case stmt in the calling method.
> ♻️ Refactor `response-data` methods to match ABNF

- lib/net/imap/response_parser.rb
* Envelope can *NOT* be `NIL`.
* Using aliased rules for envelope and address parts
* Using QUOTED_rev2 regexp for IMAP4rev2 and UTF8=ACCEPT address strings
* remove extraneous `envelope_data` method
Benchmarks:
```
Calculating -------------------------------------
v0.4.5-6-gbc32ddb2-dirty        0.4.4
bodystructure_mixed_boundary       3.379k           3.109k i/s
10.152k times in       3.004058s        3.265234s
rfc3501_8_example_3_FETCH_ENVELOPE       5.355k           4.646k i/s
15.924k times in       2.973921s        3.427366s
Comparison:
bodystructure_mixed_boundary
v0.4.5-6-gbc32ddb2-dirty:      3379.4 i/s
0.4.4:      3109.1 i/s - 1.09x  slower
rfc3501_8_example_3_FETCH_ENVELOPE
v0.4.5-6-gbc32ddb2-dirty:      5354.5 i/s
0.4.4:      4646.1 i/s - 1.15x  slower
```
> ⚡️ Simpler, faster `ENVELOPE` and `address` parser

- lib/net/imap/response_parser.rb
Note that this fixes `MBX_LIST_FLAGS` and `#mbx_list_flags`, which were previously unused, and uses them too.
This gives a significant performance boost:
```
Warming up --------------------------------------
list_with_various_flag_capitalizations            38.976k i/s
-     39.270k times in 1.007548s (25.66μs/i)
rfc3501_7.2.2_LIST_response_example            50.042k i/s
-     52.294k times in 1.044997s (19.98μs/i)
utf8_in_list_mailbox            41.722k i/s
-     44.550k times in 1.067774s (23.97μs/i)
xlist_inbox            43.242k i/s
-     46.387k times in 1.072725s (23.13μs/i)
Calculating -------------------------------------
v0.4.5-8-g4611404d       0.4.5
list_with_various_flag_capitalizations            39.943k     35.777k i/s
-    116.927k times in 2.927367s 3.268215s …
```
> ⚡️ Simplify and speed up `mailbox-list` parsing

- .github/workflows/test.yml
See https://github.com/rubygems/rubygems/issues/7329
> ✅ Limit CI rubygems for 2.7 compatibility

- test/net/imap/test_imap.rb
I've been working on a validating search syntax, so we can eventually deprecate all automatic usage of RawData.  There will be a much bigger test suite for that change.  But the full stack test (using FakeServer) doesn't need much more than this, for now.
> ✅ Add basic test for SEARCH / UID SEARCH command

- lib/net/imap/config.rb
- test/net/imap/test_config.rb
Promote the v0.5 config to be the new default config.
> 🔧 Update config for v0.5

- lib/net/imap/config.rb
This should have been done as part of #305, but was forgotten.
> 📚 Update Config rdoc for v0.5

- lib/net/imap/sequence_set.rb
- test/net/imap/test_sequence_set.rb
I'm surprised there was no test for this!
> 🐛 Fix SequenceSet[input] for a SequenceSet input

- lib/net/imap/sequence_set.rb
- test/net/imap/test_sequence_set.rb
This was broken by #319 (which hasn't been in a release yet)
> 🐛 Fix Set inputs for SequenceSet

- lib/net/imap/sequence_set.rb
- test/net/imap/test_sequence_set.rb
It's a silly mistake, but it had no test coverage.
I'm sure I did have this working at one point, but no test coverage!
> 🐛 Fix SequenceSet.try_convert

- lib/net/imap/sequence_set.rb
- test/net/imap/test_sequence_set.rb
> Backport #349: 🐛 Fix SequenceSet.try_convert

- lib/net/imap.rb
- lib/net/imap/search_result.rb
* Better `IMAP4rev2` documentation on standard commands
* Fix mistake in `SearchResult#to_s`
> 📚 Fix rdoc issues

- lib/net/imap.rb
- lib/net/imap/response_reader.rb
- test/net/imap/test_response_reader.rb
Backports #433 to `v0.4-stable`
> ♻️ Extract ResponseReader from get_response (backport #433)

- lib/net/imap.rb
Backports #418 (including tweak from #437) to `v0.2-stable`.
> 📚 Add docs for receiver thread & server responses (backport)

- test/net/imap/test_sequence_set.rb
Backports #464 to `v0.4-stable`
> ✅ Backport `SequenceSet` tests to 0.4

- lib/net/imap/config/attr_type_coercion.rb
Fixes #527.
@ko1 Do you see any issues with doing it this way?  It passes tests for me using ruby HEAD.
> 🐛 Fix loading of Net::IMAP::Config for JRuby
