lib/net/imap.rb
test/net/imap/test_imap_response_parser.rb

Zimbra server can send an untagged response "* NOOP\r\n" in order to
keep alive connection during long-running requests. These responses are
not syntactically correct, but can be safely ignored.
Add Net::IMAP::IgnoredResponse, and use it for this case.
Fixes ruby/net-imap#2

Add Net::IMAP::IgnoredResponse

---

lib/net/imap.rb
test/net/imap/test_imap_response_parser.rb

In RFC3501, `capability-data` is found both in `response-data` and in
`resp-text-code`.  Many IMAP servers return `CAPABILITY` codes in the
server greeting or in the tagged `OK` for `STARTTLS`, `LOGIN`, or
`AUTHENTICATE`.
This adds parsing for `CAPABILITY` data in a `ResponseCode`, the same as
already existed for `CAPABILITY` data in an `UntaggedResponse`.
This also fixes `resp-text` to properly match the text that comes after a
`resp-text-code`. The extra `SP` has been removed.
n.b. I submitted this PR previously, before net-imap was gemified:
* https://bugs.ruby-lang.org/issues/16626
* https://github.com/ruby/ruby/pull/2890

Capability in response code

---

test/net/imap/test_imap.rb

edcfda4b (@nobu and @hsbt) handled this for `lib/net/imap.rb`, but missed the tests.

Convert `send` to `__send__`

---

lib/net/imap.rb
lib/net/imap/authenticators.rb
lib/net/imap/authenticators/cram_md5.rb
lib/net/imap/authenticators/digest_md5.rb
lib/net/imap/authenticators/login.rb
lib/net/imap/authenticators/plain.rb
test/net/imap/test_imap_authenticators.rb

I've started down the path of implementing #10. This PR simply copies authenticators with some minor changes, but this raises a big issue I've been meaning to ask about: SASL.  I'll open another issue to discuss that: #23.  I'm marking this as a draft, pending that discussion.
In addition to moving the authenticators to new files, I've updated the rdoc and added `authnid` support for `PLAIN`.

Extract authenticators to their own files

---

lib/net/imap.rb
lib/net/imap/command_data.rb
lib/net/imap/data_encoding.rb
lib/net/imap/errors.rb
lib/net/imap/response_parser.rb

Just a few more moves of various classes, related to #10.  Similar to c2408aa, 746757b, 24e929f, 0d43c5e, 2a9afa8, 64d1080.
All of the exception classes were moved into `errors.rb`.  And I moved `NumValidator` into `data_encoding.rb`.  `NumValidator` is currently only used internally when constructing commands, but it can also be used to validate responses (e.g. I've seen a couple of servers that attempt to send 64bit `UIDVALIDITY`! 😖)

Move NumValidator and Errors to other files

---

lib/net/imap/errors.rb
lib/net/imap/flags.rb
lib/net/imap/response_parser.rb
test/net/imap/test_imap_response_parser.rb

Removing this isn't a high priority, but...
I believe the original reason for `max_flag_count` was because of GC concerns with uncollected symbols.  However, ruby can GC symbols now.  Any unbounded memory consumption or memory leaks most likely comes from other culprits (e.g. accumulating unhandled responses).
The `max_flag_count` was added in 5049da5, 2009-11-19, during the ruby 1.9.1 series.
@shugo  What do you think?

Remove max_flag_count. Ruby 2.2+ can GC symbols.

---

lib/net/imap/flags.rb

n.b. https://github.com/ruby/rdoc/issues/345 means that the `:section:` rdoc comments won't show up in the HTML rdoc output. 🙁

Add and document flags from RFC9051

---

LICENSE.txt

I'm not entirely certain this is necessary (does our use of the RFCs for
documentation count as "fair use"?).  But it's an easy thing to add.

Adding RFC licenses

---

lib/net/imap.rb
lib/net/imap/authenticators.rb
lib/net/imap/authenticators/cram_md5.rb
lib/net/imap/authenticators/digest_md5.rb
lib/net/imap/authenticators/login.rb
net-imap.gemspec
test/net/imap/test_imap_authenticators.rb

Mark obolete SASL mechanisms as deprecated (fixes GH-55):
* This is a backwards-compatible alternative to the approach here: GH-58.  We can still use that incompatible approach in a future version.
* Warn every time a deprecated mechanism is used.
* Warnings can be disabled with `warn_deprecation: false`
* Fixes GH-56: delay loading standard gem dependencies until
`#initialize`, and convert the gems to development dependencies.
Additionally:
* Adds basic tests for every authenticator (to avoid another GH-52!)
* Fixes a frozen string bug in DigestMD5Authenticator.
* Fixes constant resolution for exceptions in DigestMD5Authenticator.
* Can register an authenticator type that responds to #call (instead of
#new).  I was originally going to register deprecated authenticators
with a Proc that …

Warn when using deprecated SASL mechanisms

---

lib/net/imap.rb
lib/net/imap/response_parser.rb
test/net/imap/test_imap.rb

Fixes #36.
Added the `UID EXPUNGE` command and parses the `APPENDUID`, `COPYUID` and `UIDNOTSTICKY` responses.
I also modified the `append`, `copy` and `move` methods to return those UIDs when they are present in the response.
I have also tested this against a production Dovecot IMAP server and a Microsoft 365 account.

Support `UIDPLUS` extension

---

Rakefile

When multiple versions of "test/unit" are installed, the Gemfile.lock can be out of sync with "test/unit" version selected without bundler. When that happens, "bundle exec rake" fails, even when "rake" passes.
This can generally be fixed by simply running "bundle update" so the lockfile has the latest version, too.  And the lockfile is gitignored so this doesn't affect CI.  But, the error can be confusing and waste time.

Fixes "bundle exec rake" clash with test/unit

---

lib/net/imap.rb
lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_parser.rb

* 🐛  Bug fixed: `uid-range` should behave the same, regardless of order.  i.e. "2:4" and "4:2" are equivalent.
* 🐛 Reversed a breaking change: The return values of Net::IMAP#copy, #move, #uid_copy, #uid_move, and #append are incompatible with all previously released versions.  That would break any apps that expect the tagged response.  TaggedResponse is more broadly useful anyway, since it contains the response code with its data.
* Forward compatibility with `MULTIAPPEND`:  I converted "append-uid" to parse a "uid-set" instead of a "uniqueid".  This also provides a consistent interface: assigned_uids will always be an array of ints.
* Replaced arrays with a `UIDPlusData` struct.  In my opinion, it's much nicer to use a Struct than a "tuple". This also provides a home for documentation …

Fix some UIDPLUS issues

---

lib/net/imap/command_data.rb
lib/net/imap/data_encoding.rb
net-imap.gemspec
test/net/imap/test_imap_data_encoding.rb

Fixes date-time format, and adds decode_datetime.
Also:
* adds "date" gem as a dependency
* adds Date handling to `send_data`.  This will be used by search.
* reduce duplication by using encode_datetime in send_time_data.
I don't know if anyone is actually *using* Net::IMAP.format_datetime. *If* they are, then fixing the bug will not be backwards compatible. Since "encode" and "decode" are a natural pair (and we already had "encode_utf7"), I added new methods with those names and added deprecation warnings to the old methods.

Fixes date-time format, and adds decode_datetime

---

lib/net/imap.rb
test/net/imap/test_imap.rb

This PR fixes #40, which is one of the simplest missing commands for IMAP4rev2 support (#12).

Add the UNSELECT command

---

lib/net/imap.rb
lib/net/imap/response_data.rb
rakelib/rfcs.rake

For simple ag/ack/rg/grep during development, I've added even more RFCs to the rake file.
Additionally, I updated and reformatted the "References" section... again.  See my comments on 981ea30.

RFCs and references

---

lib/net/imap.rb
lib/net/imap/errors.rb
lib/net/imap/response_data.rb
rakelib/rfcs.rake

I propose that:
* We should deprecate `client_thread`.  This PR only marks it with `:nodoc:`.
* We should ark `RESPONSE_ERRORS` with `:nodoc:`.  We don't need to break it if people are using it, but it's an internal implementation detail, in my opinion.
* Don't need to document the `openssl extensions must be installed` scenario.  We can still try to _support_ that use-case, but "openssl" has been a default gem for a long time.
Although some installations may still disable it, this is very rare and not important enough to document here any more.  Looking at `net-http` and `net-smtp`, neither of them still document the scenario where "openssl" is missing.  Although it carefully avoids an implicit dependency, "net-http" doesn't try to catch any LoadError when an SSL connection is explicitly …

Nodocs and remove warning

---

lib/net/imap/response_parser.rb

There's no reason not to include at least very basic user-visible docs for ResponseParser.  I've been using Net::IMAP::ResponseParser (both separate from and combined with the rest of the Net::IMAP client, both my forked version and the upstream version) for over a decade. 😄
Also, I want to consider adding some parser options, e.g. "#{provider} quirks mode" vs "strict mode" vs "support experimental draft rfc", and it would make the most sense to document options those here.

ResponseParser docs

---

Rakefile

This reverts commit 6864428c763a6455c9f5cd57279b66c3443de0ae.
This breaks `test-bundled-gems` on ruby/ruby CIs.
https://github.com/ruby/ruby/actions/runs/3704473681/jobs/6277137022#step:16:259
```
/home/runner/work/ruby/ruby/build/ruby -C /home/runner/work/ruby/ruby/src/gems/src/net-imap /home/runner/work/ruby/ruby/src/.bundle/bin/rake test
/home/runner/work/ruby/ruby/src/lib/bundler/resolver.rb:263:in `raise_not_found!': Could not find gem 'digest' in locally installed gems. (Bundler::GemNotFound)
```

Revert "Fixes "bundle exec rake", clash with test/unit"

---

.github/workflows/test.yml
lib/net/imap.rb
lib/net/imap/authenticators.rb
net-imap.gemspec

Argument forwarding was the issue in #68, and we decided to require ruby 2.7 instead of adding `ruby2_keywords`.
If I remember correctly, v2.7.0-v2.7.2 didn't allow `...` to be used with leading arguments, so this sets the minimum version to v2.7.3.

⬆️ Drop v2.6 support; Require v2.7.3; Use "..." arg

---

lib/net/imap.rb

My initial PR coerced host to a string and port to an Integer and froze both.  I removed all of that, so now the PR is simply `attr_reader :host, :port`.

✨ Add attr_readers for @host and @port

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Calling `#responses` with no arguments or block is deprecated, as it
can't be made thread-safe and backward-compatible.  For convenience, an
optional `type` paramater has been added to `#responses`, to yield only
the array for that type of response.
Added `#clear_responses` as a convenience method for the common "read
and delete" pattern, and to provide a thread-safe responses
method that doesn't require a block.
The response handlers methods are synchronized, but `#response_handlers`
now returns a frozen clone to alert users who had manipulated it
directly.  Hopefully very few are affected, but this change is backwards
incompatible.  N.b: there currently is no API for inserting a
response handler into a particular position in the array.
Also, improve yields_in_test_server_thread test …

💥 Changes to responses handling, motivated by thread-safety

---

lib/net/imap.rb
test/net/imap/test_imap.rb

This simplifies caching of the server capabilities, as many servers will send their capabilities inside the greeting.  It's needed for #31.
The PR is based on #93 only because my test for it is based on that branch.  But that PR is a bigger change than this one, so I can rebase this and give it its own test, if necessary.

✨ Add greeting code data to responses

---

benchmarks/stringprep.yml
lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/stringprep.rb
lib/net/imap/stringprep.rb
lib/net/imap/stringprep/saslprep.rb
lib/net/imap/stringprep/saslprep_tables.rb
lib/net/imap/stringprep/tables.rb
rakelib/saslprep.rake
rakelib/string_prep_tables_generator.rb
test/net/imap/test_saslprep.rb
test/net/imap/test_stringprep_tables.rb

Some simple code reorg, prior to adding the `trace` stringprep for `ANONYMOUS` SASL.  I'm leaving aliases from the current locations, so it should be compatible with the currently documented API.
I'm also moving to use `autoload` with the SASL and StringPrep code as much as possible.  Most Net::IMAP users will never need to load the stringprep tables.

🚚 Move the StringPrep module out of SASL

---

rakelib/ghpages.rake

https://ruby.github.io/net-imap is now configured to automatically publish the docs directory of the gh-pages branch.  This is the current version of the rake task I used to create that branch.
This (or something like it) should be able to run from a Github action, to automatically update after every new release is tagged.  But it can be run manually until that is set up.
There are probably better ways to post the latest documentation to https://ruby.github.io/net-imap, so this may be just a temporary solution.

📚 Add "rake ghpages" for publishing rdoc

---

benchmarks/generate_parser_benchmarks
benchmarks/parser.yml
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/acl_responses.yml
test/net/imap/fixtures/response_parser/body_structure_responses.yml
test/net/imap/fixtures/response_parser/capability_responses.yml
test/net/imap/fixtures/response_parser/continuation_requests.yml
test/net/imap/fixtures/response_parser/enabled_responses.yml
test/net/imap/fixtures/response_parser/expunge_responses.yml
test/net/imap/fixtures/response_parser/fetch_responses.yml
test/net/imap/fixtures/response_parser/flags_responses.yml
test/net/imap/fixtures/response_parser/id_responses.yml
test/net/imap/fixtures/response_parser/list_responses.yml
test/net/imap/fixtures/response_parser/mailbox_size_responses.yml
test/net/imap/fixtures/response_parser/namespace_responses.yml
test/net/imap/fixtures/response_parser/quirky_behaviors.yml
test/net/imap/fixtures/response_parser/resp_code_examples.yml
test/net/imap/fixtures/response_parser/resp_cond_examples.yml
test/net/imap/fixtures/response_parser/resp_text_responses.yml
test/net/imap/fixtures/response_parser/rfc3501_examples.yml
test/net/imap/fixtures/response_parser/search_responses.yml
test/net/imap/fixtures/response_parser/status_responses.yml
test/net/imap/fixtures/response_parser/thread_responses.yml
test/net/imap/fixtures/response_parser/uidplus_extension.yml
test/net/imap/net_imap_test_helpers.rb
test/net/imap/test_imap_response_data.rb
test/net/imap/test_imap_response_parser.rb

The two big motivations for this:
1) ✅ to simplify generation of test data from RFCs or other sources.
2) 📈 to simplify re-use of test data as benchmark data.
Currently defined test types:
* `:parser_assert_equal`: compares parse result to the `expected` data.
* `:parser_pending`: print out yaml which can be inserted into the
appropriate yaml test fixture file.
* `:assert_parse_failure`: asserts `ResponseParseError` is raised
If there is no explicit test type, but there is a `:response` and an `:expected` key, then `:parser_assert_equal` is assumed.
If there is no explicit test type, but there is a `:response` without an `:expected` key, then `:parser_pending` is assumed.
This _should_ **simplify** adding new examples, but it needs to be documented.  We must not allow it to become a …

✅ 📈 Move most parser tests to yaml, add more tests, and add parser benchmarks

---

benchmarks/generate_parser_benchmarks
benchmarks/parser.yml
lib/net/imap.rb
lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb
test/net/imap/fixtures/response_parser/utf8_responses.yml
test/net/imap/net_imap_test_helpers.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_parser.rb

Split off from #104, this PR updates how `text` and `quoted` are handled (without the other bugfixes and updates in that PR).
* Fixes #110
* Fixes #38
* Fixes #109

✨ Parse UTF-8 encoded strings, for UTF8=ACCEPT and IMAP4rev2

---

lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb
test/net/imap/fixtures/response_parser/namespace_responses.yml

n.b, this was split off from #104, which was too big for a single PR.
I misread or misunderstood the spec when I first implemented this... I wrongly inserted SP-delimiters.  Most servers don't list more than one namespace, so probably very few noticed the bug!
Also:
* ♻️ Rewrote using "new parser style" to more directly imitate the ABNF.
* ⚡️ Small but measurable performance improvement.
* ♻️ Add ParserUtils::Generator#def_token_matchers for quoted, string, nil, tagged_ext_label, etc.
* ♻️ Move atom, astring, nstring, etc to top, so they can be aliased.
* ♻️ Use NIL in nstring, nquoted

🐛 Fix NAMESPACE parsing (and other ♻️ refactoring)

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb
test/net/imap/fixtures/response_parser/body_structure_responses.yml

_n.b. this was split off from #104 as its own PR._
✨ Add missing "location" extension data.
This was missing from RFC2060 but part of RFC3501. It was also missing from Net::IMAP... until now! 😄
🐛 Fix several bugs.  Most importantly:
* More strict about where `NIL` is not allowed, e.g: `number`, `envelope`, and `body`.  Ignoring these uncommon bugs made it difficult to workaround much more common server bugs elsewhere.
* 🗑️ `BodyTypeAttachment` and `BodyTypeExtension` won't be returned any more and the constants have been deprecated.
* Better workaround for multipart parts with... zero parts.
🚧 TODO: Although this will parse *most* strange BODYSTRUCTURE msg-att found in the wild, a future PR will backtrack on parse errors and try one or more "fool-proof" algorithms that partially parse …

✨🐛 Update BODYSTRUCTURE parser; add location; fix bugs

---

lib/net/imap.rb
lib/net/imap/command_data.rb

This really just makes testing a little bit more convenient, and avoids a warning when someone uses a utf8 string in code like `foo.select("æ")`.

Minor bits for UTF8=ACCEPT 

---

lib/net/imap.rb

This was the only unsynchronized access of `@responses` that I saw, so long as the private `record_responses` method is only called inside the mutex, or before the initializer returns and the receiver thread has started.

🧵 Synchronize @responses update in thread_internal

---

net-imap.gemspec
rfcs/rfc3454.txt

We generate `rfcs/rfc3454-stringprep_tables.json` from RFC3454, and generate the regexps in both `lib/net/imap/stringprep/tables.rb` and `lib/net/imap/stringprep/saslprep_tables.rb` using those tables extracted from RFC3454.  The JSON data is also used to validate that the regexps are still valid, as we use Unicode character classes which can be updated every year, and thus with every new version of ruby.
However, this means that the test suite cannot be run offline (unless you have previously downloaded RFC3454).  Adding the text version of RFC3454 solves this issue.
Fixes #136.

✅ Add RFC3454 data, to support offline testing

---

lib/net/imap/response_parser/parser_utils.rb

This adds `lookahead_{token}!` to `def_token_matchers`, as a lookahead version of match, returning the value without consuming the token.
`lookahead_case_insensitive_string!` is a fallback for the regexp in `body_type_1part`.  This fallback should be invoked only very rarely.
Its definition was lost when rebasing.

🐛 Add missing lookahead_case_insensitive_string!

---

test/net/imap/fake_server.rb
test/net/imap/fake_server/command.rb
test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/command_response_writer.rb
test/net/imap/fake_server/command_router.rb
test/net/imap/fake_server/configuration.rb
test/net/imap/fake_server/connection.rb
test/net/imap/fake_server/connection_state.rb
test/net/imap/fake_server/response_writer.rb
test/net/imap/fake_server/session.rb
test/net/imap/fake_server/socket.rb
test/net/imap/test_imap.rb

This was written for several reasons:
* To improve `yields_in_test_server_thread` and clean up tests using it
* To support new tests for #156
* To speed up adding test coverage for commands, both new and old
* Because I kept messing up `OpenSSL::SSL::SSLSocket#accept`, even
though I copied and pasted from `imaps_test` and `starttls_test`. 😳
* To support testing of other libraries and applications that use Net::IMAP.
I will (probably) eventually update most of the tests in `test_imap.rb` to use `FakeServer`.  The version here is able to support the capabilities tests and several more existing tests.  To quote the rdoc:
> **NOTE**: API is experimental and may change without deprecation or warning.
>
> FakeServer is simple fake IMAP server that is used for testing Net::IMAP.  It contains …

🧪 Add experimental new FakeServer for tests

---

lib/net/imap.rb
lib/net/todo.rdoc
test/net/imap/fake_server.rb
test/net/imap/fake_server/socket.rb
test/net/imap/fake_server/test_helper.rb
test/net/imap/test_imap_capabilities.rb

Updated methods:
* `#initialize` - save capabilities in `OK` or `PREAUTH` greeting
* `#capability` - always update saved capabilities
* `#starttls` - always clear capabilities after tagged OK response
* `#authenticate` - clear capabilities or update from tagged OK response
* `#login` - clear capabilities or update from tagged OK response
New methods:
* `#capable?(name)` - the primary API for discovering capabilities
* `#auth_capable?(name)` - returns whether a SASL mechanism is supported
* `#auth_mechanisms` - returns the server's supported SASL mechanisms
* `#capabilities` - calls `capability` when needed
* `#capabilities_cached?` - whether capabilities are cached
* `#clear_cached_capabilities` - clears the cache
Fixes https://github.com/ruby/net-imap/issues/31
Related issues:
* Fixes …

✨ Cache server capabilities and add `#capable?(name)`

---

lib/net/imap.rb

These should have been included in the previous PR:
* #156

📚 More rdoc updates, all related to capabilities

---

lib/net/imap/authenticators/digest_md5.rb
test/net/imap/test_imap_authenticators.rb

🔒️ Backport #160: Fix for Digest MD5 bad challenges

---

lib/net/imap.rb
lib/net/imap/authenticators/plain.rb
lib/net/imap/authenticators/xoauth2.rb
lib/net/imap/sasl.rb
test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/command_router.rb
test/net/imap/fake_server/configuration.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_authenticators.rb
test/net/imap/test_imap_capabilities.rb

Fixes #34. 
I decided to enable SASL-IR by default.  Because it checks server capabilities (both `capable?("SASL-IR")` `#auth_capable?(mechanism)`), this should be safe.
This is the first command in `Net::IMAP` to change its behavior based on `#capabilities` (but not the last).

✨🔒 Add SASL-IR support

---

test/net/imap/fake_server/test_helper.rb
test/net/imap/test_imap.rb

The module was originally extracted from this code, and this was accidentally left behind when `Net::IMAP::FakeServer::TestHelper` was originally committed.

♻️ Use Net::IMAP::FakeServer::TestHelper

---

lib/net/imap/stringprep.rb
lib/net/imap/stringprep/nameprep.rb
test/net/imap/test_stringprep_nameprep.rb
test/net/imap/test_stringprep_profiles.rb

This isn't used by or needed for Net::IMAP, but adding a new profile is trivial with the new generic stringprep code.  Nameprep is used by IDNA, and not useful without punycode.  But, with the addition of punycode, Net::IMAP could also support IDNA hostnames.
On the other hand, IDNA and punycode should probably be added to `uri`, not `net-imap`.  Perhaps `stringprep` should be extracted to its own gem?

✨ Add Nameprep stringprep profile

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Returns true after the TLS negotiation has completed _and_ the remote hostname has been verified.
This can be used, for example, by automated safeguards against selecting particular SASL mechanisms—or against authenticating at all—when TLS hasn't been established _and_ verified the peer.

🔒 Add Net::IMAP#tls_verified?

---

lib/net/imap.rb
lib/net/imap/authenticators.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap_authenticators.rb
test/net/imap/test_regexps.rb

* `Net::IMAP#authenticate` still behaves identically to before
* `Net::IMAP::PlainAuthenticator` and `Net::IMAP::Xoauth2Authenticator` have been moved to `Net::IMAP::SASL::PlainAuthenticator` and `Net::IMAP::SASL::XOAuth2Authenticator`.  The original constants still work but are deprecated.
* `Net::IMAP::DigestMD5Authenticator`, `Net::IMAP::LoginAuthenticator`, and `Net::IMAP::CramMD5Authenticator` were also moved to `Net::IMAP::SASL`.  The original constants have simply been removed.
* `Net::IMAP::Authenticators` has also been moved to `Net::IMAP::SASL` and has been converted to a class (with a default global instance).  The original mixin module still exists and delegates to `Net::IMAP::SASL`, but it is deprecated.

🚚 Move and rename SASL authenticators

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/stringprep.rb

SASL doc updates

---

lib/net/imap/sasl/authenticators.rb
test/net/imap/test_imap_authenticators.rb

Allow case-insensitive strings and symbols for the SASL mechanism name with `Net::IMAP::SASL.authenticator` (and thus `Net::IMAP#authenticate`).

♻️ Make SASL.authenticator case insensitive

---

lib/net/imap/sasl/authenticators.rb

In addition to selecting the constant based on the name, this also lazy loads the authenticator definitions.  Most authenticators are never used, so this avoids the cost of loading them all.

♻️ Simplify lazy-loaded SASL::{Name}Authenticator registration

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/gs2_header.rb
lib/net/imap/sasl/oauthbearer_authenticator.rb
test/net/imap/test_imap_authenticators.rb

Also, GS2Header was extracted from OAuthBearerAuthenticator.  It's not much, but it can be re-used in the implementation of other mechanisms, e.g. `SCRAM-SHA-*`.
* Fixes #80

🔒 Add SASL OAUTHBEARER mechanism

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/anonymous_authenticator.rb
lib/net/imap/sasl/authenticators.rb
test/net/imap/test_imap_authenticators.rb

🔒 Add SASL ANONYMOUS mechanism

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/external_authenticator.rb
test/net/imap/test_imap_authenticators.rb

🔒 Add SASL EXTERNAL mechanism

---

lib/net/imap.rb
test/net/imap/fake_server/test_helper.rb
test/net/imap/test_imap.rb

`Net::IMAP#ssl_ctx` will return the `OpenSSL::SSL::SSLContext` used by the `OpenSSL::SSL::SSLSocket` when TLS is attempted, even when the TLS handshake is unsuccessful.  The context object will be frozen.  It will return `nil` for a plaintext connection.
`Net::IMAP#ssl_ctx_params` will return the parameters that were sent to `OpenSSL::SSL::SSLContext#set_params` when the connection tries to use TLS (even when unsuccessful).  It will return `false` for a plaintext connection.
Additionally, error handling for the arguments to `#starttls` was moved *before* sending the command to the server.  This way a simple argument error will still raise an exception, but won't result in dropping the connection.  Because `ssl_ctx` is also created ahead of time, this will also catch invalid SSLContext …

🔒 Add `ssl_ctx` and `ssl_ctx_params` attr readers

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/anonymous_authenticator.rb
lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/external_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
lib/net/imap/sasl/oauthbearer_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap_authenticators.rb

Because the documentation for `Net::IMAP#authenticate` and `Net::IMAP::SASL` both point at the individual authenticators to document their own parameters, it's important that all of the authenticators have documentation of their own.  `PLAIN` and `XOAUTH2` in particular both needed more documentation than they had.  This PR fixes that, in addition to a few other documentation-related changes.
Each configuration parameter was given an `attr_reader` (except for CRAM-MD5 and LOGIN, which are deprecated).  In addition to being useful for debugging, the attributes are documented in more detail than the same `#initialize` parameters.  In a few cases, ivars were renamed to normalize the parameter names between different authenticators.
Several internal-use constants were made `private`, which …

📚 Update SASL docs and add attr_readers

---

lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/external_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap_authenticators.rb

All SASL authenticators have been updated to take keyword arguments.  Parameters with the same semantics (or very similar) have been given the same name across all authenticators, and unknown keywords are ignored.  This can allow the same "credentials hash" to be used with multiple authenticators.
`ArgumentError` will be raised for missing required arguments and for conflicting positional vs keyword arguments.

♻️ Allow keyword args on all SASL authenticators

---

lib/net/imap.rb
lib/net/imap/deprecated_client_options.rb
test/net/imap/fake_server/test_helper.rb
test/net/imap/test_deprecated_client_options.rb

Since 2007, `.new` and `#starttls` have taken an options hash (bad00272) and the original parameters have been undocumented (e631911e).  The original `usessl`, `certs`, and `verify` parameters will now print a deprecation warning whenever they are used.  In a future release (no sooner than a year after 0.4.0 is released), they will be removed from both methods.
The `options` hash has been converted to keyword parameters.  An. sending `port` as the second argument to `#initialize` is also obsolete.  Neither of them will print a deprecation warning, but they _will_ be marked as deprecated in a future release.
To simplify the implementations of both `#initialize` and `#starttls`, the backwards compatible parameters have all been extracted to a `DeprecatedClientOptions` module, which is …

🗑️ Deprecate backward compatible parameters to `new` and `starttls`

---

lib/net/imap.rb
test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/test_helper.rb

A logout command that also disconnects, even if logout raises an exception, and doesn't raise exceptions when already disconnected would be very useful in situations where the connection MUST be gracefully closed, e.g. for security or tests.
Although the change is relatively insignificant, changing #logout to also ignore exceptions and immediately call #disconnect would be backwards incompatible.  So a new method was created.

✨ Add #logout! to combine logout and disconnect 

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/anonymous_authenticator.rb
lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/external_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap.rb

The client is responsible for raising an error if the command completes successfully but "done?" returns false.
This is needed in order to correctly implement `SCRAM-*`:
* #54
* #172
Without this PR, if the server returns OK before sending its final message, then we can't satisfy the following requirement from the RFC:
> The client then authenticates the server by computing the
> ServerSignature and comparing it to the value sent by the server. If
> the two are different, the client MUST consider the authentication
> exchange to be unsuccessful, and it might have to drop the
> connection.
Note that this PR adds `Net::IMAP::SASL::Error` (inheriting from `StandardError`, not from `Net::IMAP::Error`) and three subclasses: `AuthenticationFailed`, `AuthenticationError`, and …

🔒 Verify SASL authentication has completed

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/gs2_header.rb
lib/net/imap/sasl/scram_algorithm.rb
lib/net/imap/sasl/scram_authenticator.rb
test/net/imap/test_imap_authenticators.rb

Loosely based an initial implementation by @singpolyma at
https://github.com/nevans/net-sasl/pull/5
* Depends on #179
* Fixes #54

🔒 Add SASL SCRAM-SHA-* mechanisms

---

lib/net/imap.rb
test/net/imap/test_imap.rb

As per RFC-4959 and RFC-9051:
> To send a zero-length initial response, the client MUST send a single
> pad character ("=").  This indicates that the response is present, but
> is a zero- length string.

🐛 Fix empty SASL-IR to send "="

---

README.md
lib/net/imap.rb

The examples shouldn't be using deprecated SASL mechanisms that are supported by almost no servers.
Also added a PREAUTH check to the connections examples.

📚 Update examples with modern SASL mechanisms

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_authenticators.rb

Making some minor API changes to SASL::Authenticators.  This class hasn't been included in a release _yet_, so there's no need to deprecate anything... if the change is made _before_ the release.  :)

✨ Minor updates to SASL::Authenticators API

---

lib/net/imap/response_parser.rb

I believe this code is only executed when there is something strange in the server's response.  If I remember correctly, I've usually only encountered this from server bugs... but it's an easy work around.

🐛 Fix typo in uncommon BODYSTRUCTURE parsing code

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Based on `net-smtp`, I had added the ability to use symbols to lookup authenticator.  But it had two issues: 1) dealing with dashes vs underscores, and 2) sending the command name using flag syntax.  This fixes both issues.

🐛 Fix authenticate using Symbol mechanism name

---

lib/net/imap.rb

By converting all of the internal `@responses.delete(type)` to `clear_responses(type)`, we get empty arrays and don't need nil-checks.
* Fixes #190.
n.b: this will result in some methods sometimes returning an empty array when they previously would have returned nil: `list`, `xlist`, `getquota`, `lsub`, `expunge`, `uid_expunge`, `fetch`, `uid_fetch`, `store`, and `uid_store`.

🥅 Work around missing server responses

---

lib/net/imap.rb

an `auth_capable?` example should've been `capable?`.
`#fetch` returns an empty array, rather than nil, since #192.

📚 Fix a few documentation mistakes

---

lib/net/imap.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/authentication_exchange.rb
lib/net/imap/sasl/authenticators.rb
lib/net/imap/sasl/client_adapter.rb
lib/net/imap/sasl/protocol_adapters.rb
lib/net/imap/sasl_adapter.rb

This adds some complexity over the IMAP implementation, but it simplifies sharing the implementation between `net-imap`, `net-smtp`, and hopefully many others in the future.
~`SASL.initial_response?` and `SASL.done?` have been removed without deprecation (they haven't been in any release yet).  The logic has been moved into `SASL::ClientAdapter`.~ Done in #184.
~`#initial_response?` was added to the deprecated authenticators.  It isn't required that authenticators implement this method, but it simplifies the tests, now that `SASL.initial_response?` is gone.~ Done in #184.
_This PR has been updated to only _create_ the SASL::ClientAdapter.  Actually using it has been pushed off until a later PR: #194._

🔒⚗️ Add experimental SASL::ClientAdapter

---

lib/net/imap/sasl/anonymous_authenticator.rb
lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/external_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
lib/net/imap/sasl/oauthbearer_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/scram_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap_authenticators.rb

Different SASL mechanisms use the term "username" differently.  In general the pattern seems to be the following:
* Some mechanisms avoid using the term `username` at all, and instead use the terms Authentication Identity (`authcid`) and Authorization Identity (`authzid`).
* Some mechanisms do not distinguish clearly between `authcid` and `authzid`.  `username` may be semantically equivalent to `authcid`, `authzid`, or both.
* When the mechanism supports an explicit `authcid`) and an Authorization Identity `authzid`, `username` commonly refers to the `authcid`.
* When the authentication identity is derived from the credentials, `username` commonly refers to the `authzid`
Every mechanism's keyword arguments, positional arguments, and documentation has been updated to match this …

🔒 SASL: Clarify usage of username vs authcid vs authzid

---

lib/net/imap/sasl/cram_md5_authenticator.rb
lib/net/imap/sasl/digest_md5_authenticator.rb
lib/net/imap/sasl/login_authenticator.rb
lib/net/imap/sasl/oauthbearer_authenticator.rb
lib/net/imap/sasl/plain_authenticator.rb
lib/net/imap/sasl/scram_authenticator.rb
lib/net/imap/sasl/xoauth2_authenticator.rb
test/net/imap/test_imap_authenticators.rb

`secret` is similar to `username`: a convenient alias with ambiguous semantics.  Adding it is reasonable, but I probably wouldn't add it only for `Net::IMAP`.  However, relevant to #23, `Net::SMTP` uses it and probably others would find it useful too.

✨ Add `secret` alias (for `password`, `oauth2_token`, etc) to relevant SASL mechanisms

---

lib/net/imap.rb
lib/net/imap/sasl/authenticators.rb

Mostly fixing formatting... but a few errors were fixed too:
* `SASL::Authenticators#add_authenticator` does not print any warnings.
* `#select` should not use `@responses` ivar in example code.

📚 Fixing and formatting docs

---

lib/net/imap.rb
lib/net/imap/errors.rb
lib/net/imap/response_parser.rb
test/net/imap/test_imap.rb

Two parts (in two commits):
The documentation for `InvalidResponseError` is:
> Error raised when the server sends an invalid response.
>
> This is different from UnknownResponseError: the response has been
> rejected.  Although it may be parsable, the server is forbidden from
> sending it in the current context.  The client should automatically
> disconnect, abruptly (without logout).
>
> Note that InvalidResponseError does not inherit from ResponseError: it
> can be raised before the response is fully parsed.  A related
> ResponseParseError or ResponseError may be the #cause.
The rdoc for `UnknownResponseError` is updated to:
> Error raised upon an unknown response from the server.
>
> This is different from InvalidResponseError: the response may be a
> valid extension response and the …

🥅 Validate response tagged in the parser

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb

This is primarily about making it easier to compare the parser source code to the RFC grammar, and secondarily about making it easier to debug parse errors.  This is subjective, of course. Perhaps more importantly, many of my other parser updates will have conflicts if this isn't added first. 😉

♻️ Update `response` and `continue-req` to new parser style

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/quirky_behaviors.yml

Previously, unhandled `response-data` would attempt to parse to the end of the string using `text`.  This would fail if the string contained either literals or binary data.  The new `unparsed_response` approach simply grabs all remaining bytes (except for the final `CRLF`).  Rather than simply return string data, the response's data uses a new `UnparsedData` struct, to unambiguously signal that the result may change if a future release starts parsing the string.
The same approach has been copied over to `numeric_response`, allowing unhandled numeric responses to be handled more robustly as well.
`IgnoredResponse` was converted to a subclass of `UntaggedResponse`, and assigns any remaining unparsed text to an `UnparsedData` struct.  Other than the subclass, it is now treated like any other …

🥅 Return UnparsedData for unhandled response-data

---

lib/net/imap/response_parser.rb

* Converted the case statement to use upcase'd strings (not regexps)
* Unified `response_data` and `numeric_response` into a single case statement, using a regexp for lookahead.
* Sorted the case statement _roughly_ in the order of frequency... but I need to collect more data to reliably make a claim about that.  In the meantime, this order made sense to me... more or less.  Current standard (both RFC3501 and RFC9051) responses are (mostly) sorted first, and deprecated, uncommon, unsupported, etc responses are sorted last.

⚡ Simpler, faster `response-data` parser

---

lib/net/imap/response_parser.rb

Adds stubs (to be implemented in later PRs) for extensions to `response-data`:
* ESEARCH    - [RFC4731], [RFC9051], etc
* VANISHED   - [RFC7162]
* LISTRIGHTS - [RFC4314]
* MYRIGHTS   - [RFC4314]
* LANGUAGE   - [RFC5255]
* COMPARATOR - [RFC5255]
* CONVERTED  - [RFC5259]
* METADATA   - [RFC5464]
* UIDFETCH   - [draft-ietf-extra-imap-uidonly]
I tried to cover _all_ known extensions, but I might have missed a few... 😉
[RFC4314]: https://tools.ietf.org/html/rfc4314
[RFC4731]: https://tools.ietf.org/html/rfc4731
[RFC5255]: https://tools.ietf.org/html/rfc5255
[RFC5259]: https://tools.ietf.org/html/rfc5259
[RFC5464]: https://tools.ietf.org/html/rfc5464
[RFC7162]: https://tools.ietf.org/html/rfc7162
[RFC9051]: https://tools.ietf.org/html/rfc9051
[draft-ietf-extra-imap-uidonly]: …

✨ Update response-data w/stubs for all extensions

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/body_structure_responses.yml

Oops!  The bug was introduced by the bodystructure parsing changes in a00e2e3.
This also adds examples to improve test coverage (including this bug).

🐛 Fix unbalanced parens in `body-fld-lang` parsing

---

lib/net/imap/response_parser.rb

* Similar to #201, but for `msg-att`.
* Converted the case statement to (mostly) use upcase'd strings, not regexps.
* The case stmt clauses were sorted.  This _might_ help with speed (need better `msg-att` frequency statistics to back up that claim) but it should _definitely_ help to help avoid conflicts.
* first the most commonly seen ones (`UID` and `FLAGS`),
* then the ones in both 3051 and 9051 (sorted alphabetically),
* then the ones in 3051 that were removed from 9051,
* then `MODSEQ` (currently, the only supported attribute that's in neither 3501 or 9051).
* Rewrite the parser for `section`, `section-spec`, `header-list`, `header-fld-name`.
* Read the entire `msg-att` label for `BODY[...]<...>` _prior_ to the case stmt.  This greatly simplifies the code for reading attribute …

⚡ Simpler, faster `msg-att` parser (for fetch responses)

---

lib/net/imap/response_parser.rb

Similar to #202 and #205, but for `resp-text-code`:
* #202
* #205
**Please note:** My primary goal with this PR and the other related PRs is to merge the _foundation_ that I've been using for a wide variety of other parser improvements.  Improving performance is only a secondary goal.  Compatibility with `IMAP4rev2` and a variety of popular extensions is still more important.

⚡ Simpler, faster `resp-text-code` parser (for response codes)

---

net-imap.gemspec

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>
By default, Ruby reads files with the system's default encoding, which is not utf-8 for every system and it does not handle special characters like '§' correctly and fails to get the VERSION from the lib/net/imap.rb file as it contains special characters
https://github.com/ruby/net-imap/blob/6dda58178b47d402edb0486e48d10c7558bc9b60/lib/net/imap.rb#L149-L151

Set utf-8 encoding when looking for VERSION in the file.

---

benchmarks/parser.yml
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/flags_responses.yml
test/net/imap/fixtures/response_parser/list_responses.yml
test/net/imap/fixtures/response_parser/resp_code_examples.yml

Rather than treat all three identically, this uses a more strict parser tailored to each one.  One of my earlier tests was invalid, so that has also been fixed.
Rather than use `String#scan`, the flags lists are matched with a single regexp, and the match is split then mapped.  In my benchmarks, this is _slightly_ faster than using `String#scan`.

⚡ Update flag parsing: FLAGS, LIST, PERMANENTFLAGS

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/quirky_behaviors.yml

Unhandled _simple_ numeric responses, which contain only the numeric prefix and the response name, will now simply return the number as the response data.
`UnparsedData` was introduced by #200.  That struct has been renamed to `UnparsedNumericResponseData`, which represents data for unhandled response types with a numeric prefix.  This prefix _is_ parsed but the additional response data is not.
A simpler `UnparsedData` struct now represents data for unknown response types _or_ for unknown extensions to response types without a well-defined extension grammar.  It is currently only used by `response_data__unhandled`, but future PRs will use it anywhere we can safely extract an unparsed string from the larger response: e.g unknown response code data.

🥅 Update parsing of unknown numeric response types

---

lib/net/imap/response_parser/parser_utils.rb

Using `@str.getbyte(@pos) = int` rather than `@str[@pos] == chr` avoids the allocation of a temporary string object and allows direct identity comparison.  This gives a speedup of ~5% to most parser benchmarks.

⚡ Parse expected chars using `String#getbyte`

---

benchmarks/parser.yml
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/fetch_responses.yml

This speeds up my (new) fetch tests/benchmarks by ~10% over 0.4.3, and by 15%-30% over earlier versions.
See the compatibility comments on the related PR, which gives a greater performance boost:
* #216

⚡ Simplify `header-fld-name` parser (backward compatible)

---

lib/net/imap.rb
test/net/imap/test_imap.rb

When the server fails to send a response for certain commands, we can workaround this by simply returning an empty array.  This should work for `SEARCH`, `SORT`, `THREAD`, and `ENABLED`, each of which expects a single response.
I did not do the same for `CAPABILITY` for two reasons:
* if a mistake is made, it could break the capabilities cache.
* the server _must_ at least return a single capability (`IMAP4rev1` or `IMAP4rev2`), so a missing response may indicate bigger problems.
Related:
* #192

🥅 Return empty array for missing server response

---

lib/net/imap/data_encoding.rb
test/net/imap/test_imap_data_encoding.rb

This modifies the code added in #66 to make it more useful when `date-time` is parsed as a `quoted` string (as it currently is).  I'd prefer that ResponseParser simply parse `date-time` values as DateTime objects, but that has backwards compatibility issues.

✨ Allow `decode_datetime` to work without dquotes

---

docs/styles.css

The new rdoc styles, using grid, don't work with my existing height, position, overflow changes to the side nav.  The upstream versions are better.  🙂

💄 Fix styles.css customization for RDoc 6.6

---

lib/net/imap/fetch_data.rb
lib/net/imap/response_data.rb
test/net/imap/test_fetch_data.rb

An accessor method has been created for every supported `msg-att` in `#attr`.  These attr accessors also provide a place for documentation for each of the supported message attributes.
With one exception, all of the methods return the value from `#attr`, unchanged.  The exception is `#internaldate`, which uses `parse_time` to return a `Time` object rather than a string.
With one exception, these methods are given the same name as their `msg-att` with `"."` changed to `"_"`.  The exception is the "body section" attributes (`"BODY[#{section_spec}]<#offset}>"`), which have been given several methods (which all accept an `offset` keyword argument):
* `#message`         for `BODY[]`
* `#part(1, 2, 3)`   for `BODY[1.2.3]`
* `#text(1, 2, 3)`   for `BODY[1.2.3.TEXT]`
* `#mime(1, 2, 3)`   for …

✨ Add FetchData msg-att methods and update rdoc

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/sequence_set.rb
test/net/imap/fixtures/response_parser/status_responses.yml

Although "number" is still the default `status-att-val`, this uses
ExtensionData with RFC4466's `tagged_ext_val` for any unknown
non-numeric `STATUS` attribute.
Running the benchmarks (on my phone, without YJIT) shows a 40% speedup!
invalid_status_response_trailing_space
v0.4.4-16-g0be6b65b:     43956.1 i/s
0.4.4:     31788.6 i/s - 1.38x  slower
rfc3501_7.2.4_STATUS_response_example
v0.4.4-16-g0be6b65b:     45436.2 i/s
0.4.4:     32458.5 i/s - 1.40x  slower
status_response_uidnext_uidvalidity
v0.4.4-16-g0be6b65b:     45334.2 i/s
0.4.4:     32709.1 i/s - 1.39x  slower

⚡ Better Faster Cleaner `STATUS` parsing

---

lib/net/imap.rb
lib/net/imap/fetch_data.rb
lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/rfc8474_objectid_responses.yml
test/net/imap/test_fetch_data.rb
test/net/imap/test_imap_response_parser.rb

* Adds support for the `MAILBOXID` ResponseCode
* Adds support for the `MAILBOXID` status attribute to `#status`
* Updates `#status` rdoc
* Adds support for the `EMAILID` message attribute to `#fetch` and `#uid_fetch` and `FetchData#emailid`
* Adds support for the `THREADID` message attribute to `#fetch` and `#uid_fetch` and `FetchData#threadid`
* Fixes #39

✨ Add support for `OBJECTID` extension (RFC8474)

---

lib/net/imap.rb

The `DELETED` status attribute was added by `IMAP4rev2`.

📚 Update `#status` docs for `DELETED` (IMAP4rev2)

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/resp_cond_examples.yml

In particular, iCloud doesn't send a `SP` after `* BYE`.  Although this is technically a violation of the RFCs, RFC9051 did make `text` optional.  So, in the spirit of RFC9051 Appx E 23, we don't require a final SP when the `resp-text` is empty.
* See also https://www.rfc-editor.org/errata/eid7343
* Fixes #229

🩹 Workaround servers that don't send required `SP` when `resp-text` is empty

---

rakelib/benchmarks.rake

The UTF-8 benchmark fails without this.

📈 Fix benchmark string encoding

---

net-imap.gemspec

By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/net-imap which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/

Provide a 'Changelog' link on rubygems.org/gems/net-imap

---

lib/net/imap/response_parser.rb

The `mailbox-data` `SEARCH` response parser was refactored, as part of the work on `CONDSTORE` support.  This commit contains only the refactoring, which (coincidentally) brings a significant speed improvement:
```
invalid_search_response_multiple_result_with_trailing_space
v0.4.6-2-g3ac9912:     70865.1 i/s
0.4.6:     49505.1 i/s - 1.43x  slower
invalid_search_response_single_result_with_trailing_space
v0.4.6-2-g3ac9912:     74398.0 i/s
0.4.6:     67791.1 i/s - 1.10x  slower
rfc3501_7.2.5_SEARCH_response_example
v0.4.6-2-g3ac9912:     65968.9 i/s
0.4.6:     53490.9 i/s - 1.23x  slower
search_response_multiple_seq_nums_returned
v0.4.6-2-g3ac9912:     62777.4 i/s
0.4.6:     47852.3 i/s - 1.31x  slower
search_response_single_seq_nums_returned
v0.4.6-2-g3ac9912:     79656.5 i/s
0.4.6: …
```

⚡️ Simplify and speed up `SEARCH` response parsing

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/quirky_behaviors.yml

Outlook.com sends an extraneous `SP` in between `address` values in its envelope address lists: `env-{from,sender,reply-to,to,cc,bcc}`.  This can't be parsed by the envelope performance tuning rewrite in #232, in the v0.4.6 release.
I've had a private test for this quirk for a decade... but the test was primarily testing a different (much stranger) BODYSTRUCTURE bug, so I thought the extra SP was a transcription error and "fixed" the test... Oops!
The example comes from a real response, but all addresses have been replaced by the `faker` gem. :)

🩹 Workaround buggy outlook.com address lists

---

lib/net/imap/response_data.rb

Also adds section headers and links to RFCs and Net::IMAP methods.

📚 List all currently supported response codes

---

lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/sequence_set.rb
test/net/imap/fixtures/response_parser/status_responses.yml
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_data.rb
test/net/imap/test_sequence_set.rb

The version of SequenceSet in net-imap prior to this PR is merely a placeholder, needed in order to complete `tagged-ext` for #225.
This updates it with a full API, inspired by Set, Range, and Array. This allows it to be more broadly useful, e.g. for storing and working with mailbox state.  A better API for working with `sequence-set` is also a prerequisite for properly supporting `ESEARCH` (#115, #121).  _NOTE: The API added here is documented as experimental, but I'd like to remove that label when v0.5.0 is released._
In addition to Integer, Range, and enumerables, any object with `#to_sequence_set` can now be used to create a sequence set.  For compatibility with MessageSet, `ThreadMember#to_sequence_set` collects all child seqno into a SequenceSet.
Because mailbox state can be _very_ …

✨ Improve SequenceSet with Set, Range, Enumerable methods

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/quirky_behaviors.yml

Gmail allows (or allowed) users to create flags containing some invalid `atom-specials` chars, such as `"]"` or `SP`.  Ultimately, this isn't unambiguously parsable.  But we can workaround it.
Prior to #212, the ResponseParser simply grabbed everything inside the parentheses and then scanned through with a very liberal "flag" regexp. This PR attempts to parse it strictly at first and if that fails falls back to the "quirks mode" parser, similar to the original.
Fixes #241.
This also uses `delete_prefix!` to avoid another string allocation when converting flag strings into symbols.
-----
Benchmark results:
```
Calculating -------------------------------------
v0.4.7-6-g3f88747    0.2.3    0.3.7    0.4.2    0.4.7
fetch_msg_att_flags_and_uid           53.343k  33.978k  33.562k  34.063k …
```

🩹 Workaround invalid Gmail FLAGS response

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/rfc9208_quota_responses.yml
test/net/imap/test_imap_response_parser.rb

This has been broken since #203 (v0.4.3).  There was no test coverage over the QUOTA response parser, so I copied the example responses from RFC9208.  All but one of the examples can be parsed without any further updates to the parser, besides the bugfix.

🐛 Fix broken `QUOTA`/`QUOTAROOT` response parsing

---

lib/net/imap.rb
lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/search_result.rb
test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/command_router.rb
test/net/imap/fixtures/response_parser/rfc7162_condstore_qresync_responses.yml
test/net/imap/fixtures/response_parser/search_responses.yml
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_parser.rb
test/net/imap/test_search_result.rb

_NOTE:_ Both `#search` and `#uid_search` have been updated to return `SearchResult` rather than `Array`.  `SearchResult` inherits from `Array`, for backward compatibility.
Similarly, the `MODIFIED` response code on the tagged response to `#store` and `#uid_store` is currently only accessible by using a response handler: response code data on tagged responses isn't saved to `#responses`.  _Unlike_ with the search methods returning `SearchResult`, I did _not_ change the behavior of `#store` to return a new result object inheriting from Array.  IMO, that change would require a backward compatibility config option and a deprecation period.
* Fixes #106
_(Note: `CHANGEDSINCE` can be used already, via an undocumented non-keyword argument.)_

✨ Add support for the `CONDSTORE` extension (RFC7162)

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/quirky_behaviors.yml

The workaround for #241 (PR #246) also applies to #228.
The upstream issue (https://github.com/greenmail-mail-test/greenmail/issues/633) was fixed promptly (thanks!).  Also, greenmail is a testing fake server and I haven't seen any evidence of any "real" servers with this exact error yet.  So I don't feel that it's critical to be compatible with it...  But we _do_ need this workaround for https://github.com/ruby/net-imap/issues/241.  So it makes sense to at least document this issue in our test fixtures, for posterity.

✅ Document and test workaround for invalid "\*" in FLAGS

---

lib/net/imap.rb

sort_internal and thread_internal have an else statement that can be removed because normalize_searching_criteria(search_keys) is called anyways after the case.

Remove redundant calls in sort_internal and thread_internal

---

lib/net/imap/sequence_set.rb

This matches `Range#overlap?`, which has been added to ruby 3.3.

✨ Add `SequenceSet#overlap?` alias for `intersect?`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

* ✨ Add `SequenceSet#entries` and `#each_entry`, for unsorted iteration
* ✨ Add `SequenceSet#append`, to keep unsorted order when modifying the set
* 📚 Document `SequenceSet` "Normalized form"
Unsorted access (preserving the original order from the server response) is especially important for using with the `ESORT`, `CONTEXT=SORT`, and `UIDPLUS` extensions.
In addition to preserving the original order, duplicate numbers are not removed, nor are adjacent or overlapping ranges or numbers coalesced.

✨ Preserving sequence set order

---

lib/net/imap/sequence_set.rb

Apparently rdoc doesn't recognize the visibility modifiers when they are used with method def arguments? 🙁

📚 Workaround rdoc method visibility bug

---

lib/net/imap/sequence_set.rb

Rdoc seems to get confused with the yield in this method.  It somehow causes all of private methods to be documented as public.  Adding `:yield:` fixes it.  (I think that changing the block containing yield to be multiline _also_ fixes it, but this yield needed better docs anyway.)

📚 Workaround rdoc issue with `:yield:` and visibility

---

Gemfile
net-imap.gemspec

`base64` is extracted as bundled gems for Ruby 3.4. We should add it to dev deps.

Add base64 dev dependency

---

lib/net/imap/search_result.rb
test/net/imap/test_search_result.rb

This was backward incompatible with existing usage of search results:
* Fixes #262

🐛 Do not automatically freeze SearchResult

---

rakelib/benchmarks.rake

The bug was caused by the change to use SearchResult (which inherits from Array).

🐛 Fix parser benchmarks generation

---

.mailmap
net-imap.gemspec

I've changed my rubygems.org email address and my primary github email address (the others are still valid).
@shugo, @nobu, @hsbt In the git `.mailmap` file, I've aliased the UUID-generated email addresses from your svn commits to your ruby-lang.org email addresses.  Is this okay with you?

📧 Update gem email address and git mailmap

---

.github/workflows/test.yml

Tests are run on both Ubuntu and Mac OS, so the name "ubuntu" was misleading.  🙂

✅ Update Github test workflow name

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/body_structure_responses.yml

Hi! I'm working on (very old) project that's excessively using net-imap to access remote IMAP servers.  Since ages we have some 'imap hacks' implemented on top of net-imap. These hacks were introduced to cope with some unusual responses from IMAP servers of our customers. I thought that I'd try to 'backport' some of them if you'd consider them viable/useful. 
In this my first PR I'm 'backporting' one fix we had since 2016. Responses from some IMAP servers contained extra space like so `((\"text\" \"plain\"  (\"charset\" \"UTF-8\")`. The fix seems to be easy and should not do harm I guess. I'm not sure if the fix is idiomatic according to the recent changes in net-imap (we're bumping net-imap frim 0.3.7 to 0.4.10 right now, so how we implemented the fix long time ago might not be pretty in …

Consider extra empty space in BODYSTRUCTURE

---

.github/workflows/release-gem.yml

This requires additional configuration on the RubyGems website:
* https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
* https://rubygems.org/gems/net-imap/trusted_publishers

🔧🔒 Configure RubyGems Trusted Publishing

---

lib/net/imap.rb
lib/net/imap/data_encoding.rb
lib/net/imap/deprecated_client_options.rb
lib/net/imap/errors.rb
lib/net/imap/flags.rb
lib/net/imap/response_data.rb
lib/net/imap/sasl.rb
lib/net/imap/sasl/external_authenticator.rb
lib/net/imap/sequence_set.rb

I simply enabled vim's `spell` option and looked at each of the files.

📚 Fix many rdoc spelling mistakes

---

test/net/imap/net_imap_test_helpers.rb

Nothing fancy here... it just prints out the YAML that should make the test pass, to simplify updating the test fixture.  It's still up to the developer to inspect that YAML and make sure it's correct.

🔍 Simplify handling of ResponseParser test failures

---

BSDL
COPYING
LICENSE.txt

https://github.com/ruby/resolv/issues/45 realized me that LICENSE.txt contains only BSD-2-Clause license, while gemspec specifies both Ruby's and BSD-2-Clause license.  So I'd like to clarify the license.

Clarify the license of net-imap

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/config/attr_accessors.rb
lib/net/imap/config/attr_inheritance.rb
lib/net/imap/config/attr_type_coercion.rb
lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb
test/net/imap/test_config.rb
test/net/imap/test_deprecated_client_options.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_capabilities.rb
test/net/imap/test_imap_response_data.rb
test/net/imap/test_imap_response_parser.rb

This enables:
* per-client overrides for `Net::IMAP.debug`
* global defaults for `open_timeout` and `idle_response_timeout`
This feels like overkill for just these three config values, but it's written in the context of dozens of other future config options as indicated by #288.  And this should make adding new config options as simple as adding new `attr_accessor` (and default values) to the Config class.  Regarding the rest of the proposal in #288, this implements the basic config inheritance described there.  Note that the backward compatibility `load_defaults` mentioned by #288 has _not_ been implemented for this PR.
Two other significant implementation details, not originally mentioned in the #288 proposal:
* basic type checking and coercion has been added.  This happened as part of …

Add Config class for `debug`, `open_timeout`, and `idle_response_timeout`

---

lib/net/imap.rb
lib/net/imap/config.rb

I accidentally merged #291 without pushing this update first!  Oops.
* switch Config autoload to require_relative
* simplify defaults documentation (No need for a table for these, since they are no different between versions, and they are unlikely to change any time soon.)

♻️ Minor Config class tidy up

---

lib/net/imap/config.rb

* Convert back to rdoc markup (not markdown) by default.  Only some config attributes will want markdown (for the tables).
* Add inheritance examples.  It's better to show than to just explain.

📚 Improve Config class rdoc

---

lib/net/imap.rb
lib/net/imap/config.rb
test/net/imap/test_imap.rb

This config option becomes the default value for the `Net::IMAP#authenticate` kwarg with the same name.
By making it configurable, users can more easily opt out of the new behavior, which can force a `CAPABILITY` call.  It shouldn't generally shouldn't be necessary to avoid calling `CAPABILITY`, but... see #278!
_(NOTE: this PR depends on #291)_

🔧 Add config option for `sasl_ir`

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/config/attr_type_coercion.rb
test/net/imap/test_config.rb
test/net/imap/test_imap.rb

_(Note: #291 is a prerequisite for this.)_
This was extracted from #93 and #97, and split into a separate PR.
A new config option is added: `responses_without_block`.  This is provided as a workaround, until dependant projects can update their usage.  For now, it is set to `:silence_deprecation_warning`, but it will be set to `:warn` in v0.5 A future release may remove this backwards compatibility, but _no sooner_ than v0.6.

🔊 Add config option for `responses_without_block`

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/config/attr_accessors.rb
lib/net/imap/config/attr_inheritance.rb
lib/net/imap/config/attr_type_coercion.rb

Various updates to rdoc for:
* Net::IMAP.new
* Net::IMAP#config
* Net::IMAP#authenticate
* Net::IMAP#idle
* Net::IMAP#idle_done
* Net::IMAP::Config
_(many changes)_
* Net::IMAP::Config::Attr* modules
_(specifically, noting that the modules themselves are not stable APIs)_

📚 Update rdoc for Config and related updates

---

lib/net/imap.rb
lib/net/imap/deprecated_client_options.rb

Lists a few example SSLContext parameters in the `.new` documentation, to make it easier for people to upgrade from the deprecated SSL parameters.

📚 Improve rdoc for Net::IMAP.new ssl: params

---

net-imap.gemspec

Previously, the gemspec's `spec.files` rejection regexp:
* only matched directory names, missing `.mailmap`
* didn't attempt to match `.github/` or `.gitignore`

📦 Don't keep .github, .gitignore, .mailmap in gem

---

lib/net/imap/config/attr_accessors.rb
test/net/imap/test_config.rb

I had done this for `#dup`, but somehow missed `#clone`.
That's what tests are for! 😉

🐛 Fix Config#clone to clone internal data struct

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

These methods were originally used to implement `#load_defaults` (to finish #288), and it seems reasonable to add them to the public API.
Unlike `SequenceSet` (which I want to have a full API to match Set, Range, and Array), I want to be careful in adding any extra public methods to `Config`.  But I think these three are basic enough to be permitted.
> Returns all config attributes in a hash.
> Assigns all of the provided +attrs+ to this config, and returns +self+.
>
> Each key in +attrs+ must match an assignment method on Config.
In other words, `#update` does the same thing that `#initialize` does with its kwargs.
> Without a block, returns a new config which inherits from self.  With a block, yields the new config and returns the block's result.
I _originally_ made `#with` create a …

✨ Add Config methods: `#to_h`, `#update`, and `#with`

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

Requires #300.
Copied from the rdoc:
The effective default configuration for a specific `x.y` version of `net-imap` can be loaded with the `config` keyword argument to Net::IMAP.new.  Requesting default configurations for previous versions enables extra backward compatibility with those versions:
``` ruby
client = Net::IMAP.new(hostname, config: 0.3)
client.config.sasl_ir                  # => false
client.config.responses_without_block  # => :silence_deprecation_warning
client = Net::IMAP.new(hostname, config: 0.4)
client.config.sasl_ir                  # => true
client.config.responses_without_block  # => :silence_deprecation_warning
client = Net::IMAP.new(hostname, config: 0.5)
client.config.sasl_ir                  # => true
client.config.responses_without_block  # => :warn
client = …
```

🔧 Add versioned defaults

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

- Depends on
- #300 
- #302
- Completes #288.
-----
This is inspired by [Rails::Application::Configuration#load_defaults](https://edgeapi.rubyonrails.org/classes/Rails/Application/Configuration.html#method-i-load_defaults) in rails.
`Config#load_defaults` resets the current config to behave like the versioned default configuration for the requested version.  (See #302.)
For example, `#load_defaults` can be used to globally behave more like a specific version of `net-imap`:
```ruby
client = Net::IMAP.new(hostname)
client.config.sasl_ir              # => true
Net::IMAP.config.load_defaults 0.3
client.config.sasl_ir              # => false
```

🔧 Add `Config#load_defaults`

---

lib/net/imap/config.rb
test/net/imap/test_deprecated_client_options.rb
test/net/imap/test_imap.rb

Other than backports, maybe, these should be the last ruby 2.7 workarounds we need to make before raising the minimum ruby requirement to 3.1 (#276).

🔇 Fix ruby 2.7 warnings

---

.github/workflows/test.yml
lib/net/imap.rb
net-imap.gemspec

Ruby 2.7 EOL was 2023-03-31.
Ruby 3.0 EOL was 2024-04-23.
Currently, net-imap remains compatible with ruby 2.7.  But some of my unmerged branches do use ruby 3.1 syntax (e.g: updated pattern matching and endless method definitions).  It will be nice if I don't need to update those branches for compatibility with EOL rubies.
----
_**NOTE:** The next release after this is merged should be v0.5.0._

💥 Drop ruby 2.7 and 3.0 support, and require 3.1

---

lib/net/imap/config.rb

This was extracted from #93 and split into a separate PR.
This allows us to prepare dependent projects for the new behavior before their logs are flooded with deprecation warnings.
Also adds `Net::IMAP.attr_accessor :silence_thread_safety_deprecation_warnings`.  This is provided as a temporary workaround, until dependant projects can update their usage.

🔊 Warn about deprecated `#responses` usage

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/errors.rb
test/net/imap/test_imap_capabilities.rb
test/net/imap/test_imap_login.rb

This may be considered a "breaking change", but it should have no negative effect on well behaved servers.  This should merely change a NoResponseError into a LoginDisabledError.
However, some broken servers have been known to hang indefinitely when issued a `CAPABILITY` command prior to authentication.  For those servers, we offer the `enforce_logindisabled` config option.
Fixes #32.

🔒 Enforce `LOGINDISABLED` requirement

---

lib/net/imap/sasl/digest_md5_authenticator.rb
test/net/imap/test_imap_authenticators.rb

_(This work in this commit was done about 18 months ago, as part of #78.  In fact, the work done in this PR was used to guide the style of all of the new authenticators.  I wasn't sure whether it was worth submitting as a PR, but for the sake of completeness: here it is.)_
-----
Yes, DIGEST-MD5 is deprecated!  But that also means that it was lower risk for experimenting with other SASL changes.  Its complexity vs most other mechanisms made it a good test-bed for the completeness of net-imap's SASL implementation.  For example:
* It demonstrated that we were missing features such as `done?`.
* It demonstrates the utility of using callbacks for attributes such as `realm` (the user might select from a server-provided list).
_Please note: the initial work I did to support attribute callbacks …

🔒 SASL DIGEST-MD5: realm, host, service_name, etc

---

lib/net/imap.rb
lib/net/imap/sasl/authentication_exchange.rb
lib/net/imap/sasl/authenticators.rb
test/net/imap/test_imap_authenticators.rb

This was used in _six_ different places, so it's better to DRY up the implementation.

♻️ Extract SASL::Authenticators#normalize_name

---

lib/net/imap/command_data.rb

`DateTime` is a subclass of `Date`.  So it was sent as date.

🐛 Fix #send_data to send DateTime as time

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/fetch_responses.yml

If a header field name is quoted, `ResponseParser#header_fld_name` drops the closing quotation mark.
```ruby
parser = Net::IMAP::ResponseParser.new
parser.instance_variable_set("@str", %Q|"CONTENT-LOCATION")|)
parser.instance_variable_set("@pos", 0)
parser.instance_variable_set("@lex_state", Net::IMAP::ResponseParser::EXPR_BEG)
parser.send(:header_fld_name)
```
Expected: `"\"CONTENT-LOCATION\""`
Actual: `"\"CONTENT-LOCATION"`
`header_fld_name` extract the raw encoded value using `@str` and `@pos`.  `header_fld_name` expects `astring` to lookahead a space or a closing parenthesis but if the field name is quoted, it calls `string` method and it doesn't lookahead a token.
Adjust the range to extract depending on whether a token is looked ahead or not.

🐛 Fix #header_fld_name to handle quoted strings correctly

---

lib/net/imap/sequence_set.rb

Now that the minimum ruby version is v3.1.0, we can use `Integer.try_convert`.  This code was originally written using `Integer.try_convert`, but had to be changed for backward compatibility with ruby 2.7.

♻️ Use Integer.try_convert (new in ruby 3.1+)

---

lib/net/imap/data_encoding.rb
lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

SequenceSet's API should now be considered "stable".  This PR updates the SequenceSet documentation, to remove the "experimental" notice at the top.
This PR depends on #319, which makes a minor breaking change to the API.

📚 SequenceSet API is considered stable now

---

lib/net/imap.rb
lib/net/imap/command_data.rb
test/net/imap/test_imap.rb

There are some small differences in how `MessageSet` and `SequenceSet` behave.  I'll add a backward incompatibility warning to the release notes.
But, although the following list of changes does _seem_ long, I don't think the changes should break any existing code.  Most of the changes are bugfixes or allow something new to work that didn't work before.
These are the differences that I've noted (there may be others):
SequenceSet does almost all of its validation during construction.  The _only_ invalid SequenceSet is an _empty_ SequenceSet.  MessageSet only validates when `validate` is called.  In practice, this shouldn't make much of a difference.
MessageSet does not validate ranges at all.  This can result in exceptions _while sending the data_, which might leave the connection in a …

💥 Replace MessageSet with SequenceSet

---

lib/net/imap/sasl/client_adapter.rb
lib/net/imap/sasl/protocol_adapters.rb
lib/net/imap/sasl_adapter.rb

Several minor updates, all related to the SASL::ClientAdapter API:
* Improved `SASL::ClientAdapter` documentation.
* Added documention to `SASL::ProtocolAdapters` and each of the methods in `SASL::ProtocolAdapters::Generic`.
* `#host` and `#port` didn't make sense in `SASL::ProtocolAdapters`.  Moved them to `SASL::ClientAdapter`.
* `#service` returns the generic GSSAPI service name (`"host"`) rather than raise an exception.
* Use Forwardable: almost all of the methods simply delegate to `#client`.
* Delete `IMAP::SASLAdapter#auth_capable?`: the superclass definition is identical.

🔒 📚  Improvements and docs for SASL::ClientAdapter

---

lib/net/imap/response_parser.rb
test/net/imap/fixtures/response_parser/fetch_responses.yml

This speeds up my (newly added) benchmarks by ~15-20% over v0.4.3, and by 22-40% over earlier versions.
**NOTE:** In every version up to v0.4.3, `Net::IMAP` recreated the raw original source string.  After #217, it slices the raw original source string.  After this PR, it returns the _decoded_ astring value.  Although this is _technically_ incompatible, it should almost never make a difference.  See the [IANA Message Header Field Names list](https://www.iana.org/assignments/message-headers/message-headers.xhtml).  All standard header field names are valid IMAP atoms.  So I think this incompatibility should _almost_ never occur.
Valid RFC-5322 field names will never require string literals.  But they technically may include atom-special characters and thus need to be quoted.  Note that …

💥⚡ Simplify `header-fld-name` parser (backward incompatible)

---

lib/net/imap.rb

I don't know what the original purpose for `#client_thread` was, and it was deprecated by v0.4.0.
There's nothing particularly special about the Thread that created the client instance.  Net::IMAP doesn't use it, clients can use multiple threads, and users of Net::IMAP can track this for themselves if they need to.

💥🔥 Remove deprecated #client_thread attr_reader

---

lib/net/imap/response_data.rb
test/net/imap/test_regexps.rb

These were always a bit buggy, and they've been marked as `deprecated_constant` since v0.4, so hopefully there won't too much impact on anyone.

🔥 Drop deprecated BodyType structs

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

I'm surprised there was no test for this!
(This is a backport of #326 to `v0.4-stable`)

🐛 Fix SequenceSet[input] for a SequenceSet input

---

lib/net/imap.rb
test/net/imap/fake_server.rb
test/net/imap/fake_server/connection.rb
test/net/imap/test_imap.rb

This adds `Net::IMAP#extract_responses`, which behaves similarly to ActiveSupport's [Array#extract!](https://api.rubyonrails.org/classes/Array.html#method-i-extract-21) (which is a method I _often_ wish we had in ruby core!).
Yields all of the unhandled `#responses` for a single response type.  Removes and returns the responses for which the block returns a true value.
Extracting responses is synchronized with other threads.  The lock is released before returning.

✨ Add `#extract_responses` method

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Previously, SequenceSet modification methods would raise a frozen error when it updated its internal data structure (currently implemented as an array of arrays), which was "can't modify frozen Array: [int, int]". This was unexpected, confusing, and misleading.
This changes the SequenceSet modification methods to raise the expected FrozenError _prior_ to attempting to modify the internal data structure.

🥅 Improve SequenceSet frozen errors

---

lib/net/imap.rb
lib/net/imap/config.rb
test/lib/helper.rb
test/net/imap/test_config.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_responses.rb

Add `:frozen_dup` option to `Config#responses_without_block`.  When set to `:frozen_dup`, `IMAP#responses` called without a type or a block will return a frozen duplicate or the responses hash.  The hash's array values will also be frozen dups.  None of the values in those arrays will be frozen, but writing to those should be uncommon.  (Net::IMAP itself will never update any response structs.)
Because `responses(type)` is relatively new and has always raised an exception, we can update it to _always_ return a frozen dup array without breaking backward compatibility.  This is done _regardless_ of the config option.  The config name (`config.responses_without_block`) is a little misleading now, but it's kept for backward compatibility.  `config.responses_without_args` was added as an …

✨ New config option to return frozen dup from `#responses`

---

lib/net/imap.rb
lib/net/imap/sasl/authentication_exchange.rb

Use the experimental adapter created by #183.

♻️ Use SASL::ClientAdapter

---

test/net/imap/fake_server.rb

This backports #317 from `master` (0.5.0-dev).
What I _really_ want to backport is #330 and #334, and this is a prereq for those.

✅ Add a Mutex to FakeServer (for tests only) [backport: #317]

---

lib/net/imap.rb
test/net/imap/fake_server.rb
test/net/imap/fake_server/connection.rb
test/net/imap/test_imap.rb

This backports #330 from `master` (0.5.0-dev).

✨ Add #extract_responses method [backport: #330]

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

This backports #331 from `master` (0.5.0-dev).

🥅 Improve SequenceSet frozen errors [backport: #331]

---

lib/net/imap.rb
lib/net/imap/config.rb
test/lib/helper.rb
test/net/imap/test_config.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_responses.rb

Backports #334 from `master` (0.5.0-dev).

✨ New config option to return frozen dup from #responses [backport: #334]

---

.github/workflows/push_gem.yml

I'm not sure why dependabot didn't suggest upgrading these.  But we need to consider these actions as trustworthy, so I think that any security risk due to using a version branch (rather than a checksum) is offset by the hassle (and security risk!) of not automatically getting updates.
In particular, even if dependabot _did_ make PRs to upgrade these, it wouldn't have made a PR for the `v0.4-stable` branch.

✅ Fix GH action for rubygems Trusted Publishing

---

.github/workflows/push_gem.yml

This backports #340 from `master` (v0.5.0-dev).

✅ Fix GH action for rubygems Trusted Publishing (backport: #340)

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Returns an array with `#normalized_string` when the sequence set is valid and an empty array otherwise.

✨ Add `SequenceSet#deconstruct`

---

test/lib/helper.rb

In `ruby/ruby` repository, we can't use `simplecov-json` for `make test-bundled-gems`.
https://github.com/ruby/ruby/actions/runs/11569147158/job/32202320346#step:14:163
I added workaround for that. I'm happy to release v0.5.1 with this.

Make simplecov-json as optional dependency

---

test/lib/helper.rb

@nobu resolved installation issue for `simplecov-json` at https://github.com/ruby/ruby/pull/11969
We don't need this workaround now.

Removed needless workaround

---

lib/net/imap.rb

This should be have identical behavior to before the refactoring.

♻️  Reduce duplication in normalizing search args

---

lib/net/imap.rb
lib/net/imap/sequence_set.rb
test/net/imap/test_imap.rb

This was extracted from #345.  This adds types which will be converted into SequenceSet, so that PR can focus only on _not_ converting a few types to SequenceSet.

✨ Coerce `Set`, `:*`, `#to_sequence_set` search args into sequence-set

---

lib/net/imap.rb
test/net/imap/test_imap.rb

This affects `#search`, `#uid_search`, `#sort`, `#uid_sort`, `#thread`, and `#uid_thread#`.
Prior to this, sending a parenthesized list in the search criteria for any of these commands required the use of strings, which are converted to `RawData`, which has security implications with untrusted inputs.
With this change, arrays will only be converted into `SequenceSet` when _every_ element in the array is a valid `SequenceSet` input.  Otherwise, the array will be left alone, which allows us to send parenthesized lists without using strings and `RawData`.
For example, some searches this change enables:
* combining criteria to pass into `OR`, `NOT`, `FUZZY`, etc.
* `search(["not", %w(flagged unread)])` converts to:
`SEARCH not (flagged unread)`
* Adding return options (we should also add a …

✨ Enable parenthesized lists in search criteria

---

test/net/imap/net_imap_test_helpers.rb

This is obsolete.  The version of `yaml` that comes with the minimum ruby version now supports `unsafe_load_file`.

🔥 Drop YAML.unsafe_load_file refinement (tests only)

---

.github/release.yml

I noticed that rdoc and irb have a [release.yml].  This is slightly different from theirs.  It has all of the categories that I've been using for recent releases.  It does _not_ add emojis to the category titles, because that seems redundant when each individual PR has its own emoji. 😉
[release.yml]: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

📦📚  Add release.yml for better release note generation

---

docs/styles.css

rdoc 6.8 fixed *many* things and broke two:
* method headers (changed enough that my custom styles broke)
* description lists (gave "label" lists the "notes" list style)

📚💄 Fix rdoc 6.8 CSS styles

---

.github/workflows/test.yml
test/net/imap/test_imap.rb

@nevans I'm working to enable to test with Windows at https://github.com/ruby/ruby/pull/12193
In `net-imap`, only `test_starttls_unknown_ca` is failing at that pull-request. I make to skip that test with Windows. And I added `windows-latest` to our CI.

Enabled windows-latest on GHA

---

lib/net/imap.rb

Now that rdoc 6.8 renders properly on small screens, the IMAP#search docs needed to be updated.  Nested unordered lists indent too deeply for small screens.
Also, the search rdoc reads better when the details of argument translation are moved from the main text into its own subsection.
Also, the search key reference has been reorganized around key type.
Also, the heading levels were all adjusted to `h4` and `h5`.  This assumes that the method heading is an `h3` heading.  Unfortunately, the method headings use a `<div>`, but they _should_ be `h3` headings. 😉

📚 Update IMAP#search docs (again)

---

lib/net/imap.rb

All headings inside Net::IMAP method rdoc have been set to `h4`.  This assumes that the method documentation is already three levels deep:
* `<h1>` -- the page title, i.e: the class name
* `<h2>` -- the category, i.e: "Instance Methods"
* `<h3>` -- the method name
The first two heading levels _are_ handled correctly by rdoc, but the third level is unfortunately output as a `<div>`, not an `<h3>`.   _(*TODO*: make a `ruby/rdoc` PR to fix this.)_

📚 Consistent heading levels inside method rdoc

---

lib/net/imap/command_data.rb

The new `CommandData` superclass uses `Data` (prereq: #352) to add the pattern matching and equality methods while also simplifying the implementation.  Specifically, I wanted RawData#deconstruct for the basic `ESEARCH` support branch (#333).  It seemed reasonable to apply the same change to all of the internal command data classes.
Please note: this does change these objects to be frozen.  However, these classes are explicitly undocumented (`:nodoc`), never returned by any public methods, and considered "internal", so this will _not_ be treated as a "breaking change".  I've extracted this from #333 into its own PR purely for documentation (release notes, etc).

♻️ Refactor internal command data classes

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Previously this was an empty array, but that's incompatible: it's missing `#modseq`.

✨ Return empty SearchResult for no search result

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Extracted from #333.
Eventually, I'd like to deprecate the `charset` optional arg to `#search` (etc) and replace it with a kwarg or embedding it inside the command args array.  This is only a tiny step in that direction.  (It won't be deprecated any time soon.)

🥅 Raise ArgumentError on multiple search charset args

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Someday, I'd like to deprecate the positional `charset` parameter.  Maybe 0.7.0 can print a deprecation warning.  Meanwhile, let's make the kwarg available.

✨ Add keyword argument for search charset

---

lib/net/imap.rb
lib/net/imap/esearch_result.rb
lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/response_parser/parser_utils.rb
test/lib/helper.rb
test/net/imap/fixtures/response_parser/esearch_responses.yml
test/net/imap/fixtures/response_parser/rfc7162_condstore_qresync_responses.yml
test/net/imap/test_esearch_result.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_parser.rb

Parse `ESEARCH` into `ESearchResult`, with support for generic RFC4466 syntax and RFC4731 `ESEARCH` return data.  For compatibility, `ESearchResult#to_a` returns an array of integers (sequence numbers or UIDs) whenever any `ALL` result is available.
Gather ESEARCH response to #search/#uid_search.  If the server returns both `ESEARCH` and `SEARCH`, both are cleared from the responses hash, but only the `ESEARCH` is returned.
When the server doesn't send any search responses and return options are passed, return an empty ESearchResult.  This empty result will have the appropriate `tag` and `uid` values, but no `data`.  Otherwise return an empty `SearchResult`.
Add keyword param for search return options, and process it differently from `criteria`.  Also extract a `return` argument out of …

✨ Add basic ESearch support

---

docs/styles.css
lib/net/imap.rb

* Fix rdoc method "> Source" style (`min-content` squeezed the disclosure icon to a different line).
* Fix rdoc-ref link syntax (linking `#search` to `ESearchResult#to_a`).

📚 Fix rdoc issues

---

lib/net/imap.rb
lib/net/imap/response_data.rb
lib/net/imap/response_parser.rb
lib/net/imap/vanished_data.rb
test/net/imap/fixtures/response_parser/rfc7162_condstore_qresync_responses.yml
test/net/imap/test_imap.rb
test/net/imap/test_vanished_data.rb

`VANISHED` responses are required by two different extensions: `QRESYNC` and `UIDONLY`.
* Add a new response data type: `VanishedData`, which wraps `SequenceSet` and the `EARLIER` modifier.
* Update the parser to handle the `VANISHED` response => `VanishedData`
* Update `#expunge` and `#uid_expunge` to return `VANISHED` _(without the `EARLIER` modifier)_ responses, when they are present.
* There is a TODO note on this: For consistency, if either of the above extensions are enabled, we should return an empty VanishedResponse when the commands have no result.  Currently, an empty array is returned.
Although neither extension is completely supported yet, they can both be (partially) used in a way that doesn't crash... so I think this is a reasonable chunk to extract into its own PR, rather …

✨ Add support for VANISHED responses

---

lib/net/imap.rb

The rdoc for the `set` argument incorrectly described how `MessageSet` previously handled it, not how `SequenceSet` currently handles it. Also, `Related:` incorrectly pointed to `#uid_search`, not `#uid_fetch`.
The rdoc for `#uid_fetch` was also updated, in preparation for `PARTIAL` support (#367).

📚 Fix documentation for `#fetch`

---

lib/net/imap.rb
lib/net/imap/command_data.rb
lib/net/imap/response_parser.rb
test/net/imap/test_imap.rb

Previously, `imap.uid_search "ALL", return: ["PARTIAL", 1...500]` would wrongly encode the range to "1:500", but it should encode as "1:499".
Maybe this could have been a one line bugfix: `first, last = range.minmax`.  But the rest was written to simplify support for the `PARTIAL` extension (#367).

🐛 Fix partial-range encoding of exclusive ranges

---

lib/net/imap.rb
lib/net/imap/esearch_result.rb
lib/net/imap/response_parser.rb
rakelib/rfcs.rake
test/net/imap/fixtures/response_parser/rfc9394_partial.yml
test/net/imap/test_esearch_result.rb
test/net/imap/test_imap.rb
test/net/imap/test_imap_response_parser.rb

- Updates `#search`, `#uid_search` with the `PARTIAL` return option which adds `ESearchResult#partial` return data.
- Updates `#uid_fetch` with the `partial` modifier (kwarg).

✨ Add support for `PARTIAL` extension (RFC9394)

---

README.md
docs/styles.css
lib/net/imap/config.rb
lib/net/imap/fetch_data.rb
lib/net/imap/response_data.rb

These are some relatively minor rdoc updates, mostly for response data, and mostly just to make the documentation slightly more consistent.

📚 Documentation updates

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

When a SequenceSet is not normalized, it stores its string in `@string`.  When it is normalized, `@string` is still used as a cache for `@string`.
When `@string` isn't set, but the sequence set is not empty, `#append` would generate the normalized string _after_ adding the new numbers, and _then_ append the new numbers to the end of the string.  For example:
```ruby
SequenceSet.new.append(5).append(1).string
```
This PR forces the string to be generated prior to adding the new numbers, so they can be appended to the end.

🐛 Fix `SequenceSet#append` when its `@string` is nil

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Most methods convert their inputs into an array of range tuples.  For efficiency, SequenceSet inputs just use the internal `@tuples` array directly.  Unfortunately, the internal tuple arrays were also reused, which could cause a variety of bugs.  Fortunately, the only bug I experienced was that adding a frozen SequenceSet would result in frozen tuples being added to a mutable set.  But this could also result in modifications to one SequenceSet affecting another SequenceSet!

🐛 Fix SequenceSet merging in another SequenceSet

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

* Backports #376 
* Backports #377

🐛 Backport SequenceSet bugfixes (#376, #377) to v0.4

---

lib/net/imap/sequence_set.rb

`SequenceSet#===` is not an alias for `SequenceSet#cover?`.  It delegates to `#cover?` but handles errors differently.

📚 Fix `SequenceSet#cover?` documentation

---

lib/net/imap/response_parser.rb
test/net/imap/test_imap_response_parser.rb

When ResponseParser was initialized without any explicit config, it used Config.global directly.  This meant that changes to `parser.config` were also changes to the _global_ config!
When ResponseParser is initialized with a config hash, that creates a frozen config object.  This meant that changes to `parser.config` were impossible.
So, when the given config is global or frozen, we create a new config and inherit from the given config.  We want to continue using the given config as-is in other cases, so the client and its parser can share the same exact config.

🔧 Ensure ResponseParser config is mutable and non-global

---

lib/net/imap/response_parser.rb
test/net/imap/test_imap_response_parser.rb

* Backports #381 to `v0.4-stable`

🔧 ResponseParser config is mutable and non-global (backports #381)

---

test/net/imap/test_sequence_set.rb

`#each_range` and `#each_number` were previously tested indirectly via `#ranges` and `#numbers`, but this adds tests on them directly.

✅ Improve test coverage for SequenceSet enums

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Adds three new SequenceSet methods for querying about "duplicates":
* `#has_duplicates?`: Returns whether the ordered entries contain any duplicates.
* `#count_duplicates`: Returns the count of duplicates in the ordered entries.
* `#count_with_duplicates`: Returns the count of numbers in the ordered entries, including any repeated numbers.

✨ Add SequenceSet methods for querying about duplicates

---

test/net/imap/test_sequence_set.rb

Less duplication, still fairly easy to read, IMO.

♻️✅ Refactor SequenceSet enumerator tests

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Yields each number in the ordered `#entries` and returns `self`.

✨ Add `SequenceSet#each_ordered_number`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

In `#count`, "*" is treated as if it is effectively UINT32_MAX.  That was also the intention for `#count_with_duplicates` (add in #384, not released yet).
Unlike `#count`, which can assume that `*` only appears at most once, `#count_with_duplicates` needs to check each entry.
This means that, e.g:
```ruby
seqset = SequenceSet["#{UINT32_MAX}:*"]
seqset.count                 => 1
seqset.count_with_duplicates => 1
seqset.count_duplicates      => 0
seqset = SequenceSet["#{UINT32_MAX},*"]
seqset.count                 => 1
seqset.count_with_duplicates => 2
seqset.count_duplicates      => 1
```

🐛 Fix SequenceSet count dups with multiple "*"

---

Gemfile

This silences the warning seen when running `bin/console` in development.

➕ Add "irb" to Gemfile to silence warning

---

test/net/imap/fake_server/test_helper.rb
test/net/imap/test_imap.rb

For https://github.com/ruby/net-imap/issues/287
`OpenSSL::SSL::SSLError` is raised at 13/69 times in my macOS box. I always retried all of test suite of `ruby/ruby` everyday.
I know we should resolve this with root causes. But I have not enough time to investigate this.
And I got the following timeout issue with 4 times. 
```
#<Thread:0x00000003236f3850 /Users/hsbt/Documents/github.com/ruby/ruby/gems/src/net-imap/test/net/imap/fake_server/test_helper.rb:10 run> terminated with exception (report_on_exception is true):
/Users/hsbt/Documents/github.com/ruby/ruby/lib/timeout.rb:40:in 'Timeout::Error.handle_timeout': execution expired (Timeout::Error)
```
I extend that timeout value to handle that.
I didn't get test failed running with ten times after applying above two workarounds.

Omit flaky test with macOS platform

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Returns the first index of `number` in the ordered #entries, or `nil` if `number` isn't in the set.
This is the ordered entries version of `#find_index`.

✨ Add `SequenceSet#find_ordered_index`

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Fixes #394.
When `start_tls_session` raises an exception, that's caught in the receiver thread, but not re-raised.  Fortunately, `@sock` will now be a permanently broken SSLSocket, so I don't think this can lead to accidentally using an insecure connection.
Even so, `#starttls` should disconnect the socket and re-raise the error immediately.
Failing test case was provided by @rhenium in #394.

🥅 Re-raise `#starttls` error from receiver thread

---

lib/net/imap/uidplus_data.rb

`COPYUID` was originally (in the `UIDPLUS` extension) only allowed to be sent in the tagged response to the command which copied the messages.
Because the move commands atomically combine copy with expunge, the `MOVE` extension changed that for move commands, to recommend sending it as an untagged response prior to the tagged response for the move.  This way, `EXPUNGE` responses could also be sent prior to the completion of the `MOVE`.  `IMAP4rev2` updates that recommendation to a requirement.
However, some of the biggest email providers (most notably, GMail) follow the original `UIDPLUS` extension's requirement and still send the `COPYUID` response with the tagged response, even for move commands.

📚 Document COPYUID in tagged vs untagged responses

---

lib/net/imap/response_data.rb
lib/net/imap/uidplus_data.rb
test/net/imap/test_uidplus_data.rb

It isn't possible to convert `UIDPlusData` to use `SequenceSet` internally, while still maintaining full backwards compatibility.  So two new classes were added (`AppendUIDData` and `CopyUIDData`).  The intention is to remove `UIDPlusData` in `v0.6.0`.
* Both `AppendUIDData` and `CopyUIDData`:
* uid-set attributes are `SequenceSet` objects (not arrays of integers)
* new validations have been added to the initializers
* `data.size` to get the uid-set size
* Only `CopyUIDData`:
* `uid_mapping => source_uid_to_assigned_uid_hash`
(This behaves identically to the existing `UIDPlusData#uid_mapping`.)
* `copyuid.assigned_uid_for(source_uid) => assigned_uid`
`copyuid[source_uid] => assigned_uid`
* `copyuid.source_uid_for(assigned_uid) => source_uid`
* `copyuid.each_uid_pair` _(aliases: …

✨ Add AppendUIDData and CopyUIDData classes

---

lib/net/imap/config.rb
lib/net/imap/response_parser.rb
lib/net/imap/uidplus_data.rb
test/net/imap/test_imap_response_parser.rb

* Depends on #400
Adds `Net::IMAP::Config#parser_use_deprecated_uidplus_data` attribute.  This config attribute causes the parser to use the new AppendUIDData and CopyUIDData classes instead of CopyUIDData.
`AppendUIDData` and `CopyUIDData` are _mostly_ backward-compatible with `UIDPlusData`.  Most applications should be able to upgrade with no changes.
The plan is to remove `UIDPlusData` in `v0.6`.  To simplify upgrades, the config option can stay until `0.7`.  But, after `UIDPlusData` has been removed, maybe only allow setting it to `false` .

🔧 Add parser config for `APPENDUID`/`COPYUID`, 🗑️ Deprecate UIDPlusData

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Backports all of the following PRs to `v0.4-stable`:
* _rdoc only:_ #376
_The code changes were backported already._
* #379 
* #383 
* #384 
* #385 
* #386 
* #387 
* #396 
* #397 
With only a few simple exceptions (relating to differences in rdoc, versioned defaults in `config.rb`, and the autoloads in `response_data.rb`) cherry-picking went smoothly and without conflicts.
This adds the following new methods to `Net::IMAP::SequenceSet`:
* `#count_with_duplicates`: The ordered entries version of `#count`.
* `#count_duplicates`: The difference between `#count` and `#count_with_duplicates`.
* `#has_duplicates?`: Returns whether `#count_duplicates` is positive.
* `#each_ordered_number`: The ordered entries version of `#each_number`.
* `#find_ordered_index`: The ordered entries version of …

✨ SequenceSet ordered entries methods (backports to v0.4-stable)

---

lib/net/imap.rb
test/net/imap/test_imap.rb

Backports #395 to `v0.4-stable`.
When `start_tls_session` raises an exception, that's caught in the receiver thread, but not re-raised.  Fortunately, `@sock` will now be a permanently broken SSLSocket, so I don't think this can lead to accidentally using an insecure connection.
Even so, `#starttls` should disconnect the socket and re-raise the error immediately.
Failing test case was provided by @rhenium in #394.

🥅 Re-raise `#starttls` error from receiver thread (backport #395 to v0.4)

---

lib/net/imap/response_parser.rb
test/net/imap/test_imap_response_parser.rb

Prior to ruby 3.3, `Range#count` is handled by `Enumerable#count`, even for numeric ranges.  For large ranges, `Range#size` is _significantly_ faster.  On my system, ruby 3.2 took 54 seconds (at 100% CPU) to run `(1...2**32).count`.
Thanks to @xiaoge1001 for reporting this issue (Fixes #410).

🐛 Use `Range#size` vs `Range#count` for `uid-set` limit

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

This reorganizes the creation of `Config.version_defaults` to make it easier to cherry-pick backported config changes to stable branches, and to require fewer updates for new `x.y.0` releases:
* Sets `Config[0.5]` as a diff from the previous versioned default, just like the other versioned defaults.
* Sets `Config[:current] = Config[VERSION.to_f]`, so it will not need to be updated for any x.y.0 release.  Likewise, sets `Config[:next]` and `Config[:future]` to `Config[VERSION.to_f + 0.1]` or `+ 0.2`, so they which will only rarely need to be changed.
* Because `Config[:default]` and `Config[:current]` are now derived two different ways, both a warning and a test have been added to ensure they remain synchronized.
* A few other `Config.version_defaults` tests were added or updated.

♻️ Reorganize `Config.version_defaults` creation

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

This backports #412 to `v0.4-stable`, which should make it easier to cherry-pick other backported config changes to stable branches (with fewer merge conflicts).

♻️ Update versioned default configs (backports #412)

---

test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/connection.rb
test/net/imap/fake_server/test_helper.rb

When the client disconnects without a `LOGOUT`, that shouldn't cause a secondary error in the test output.  Most of the time, it's just a distraction.  In some cases, the test is intentionally triggering a bad disconnect, and the server's failure could break the test.

✅ Make FakeServer more robust against disconnect

---

test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/command_router.rb
test/net/imap/fake_server/socket.rb
test/net/imap/fake_server/test_helper.rb

Most importantly, transforming basic command parse error into IOError after EOF, enabling `with_fake_server(ignore_io_error: true)` to be usable for more test cases.

✅ Improvements to FakeServer (tests only)

---

lib/net/imap.rb
lib/net/imap/connection_state.rb
test/net/imap/test_imap_connection_state.rb

Tracking IMAP connection state has many uses.  But in this PR, we're only tracking the session state and exposing a `#connection_state` attribute reader.
For forward-compatibility, the only documented methods on the connection state objects are (currently) `#name` and `#to_sym`, which will return one of `not_authenticated`, `authenticated`, `selected`, or `logout`.
From RFC9051:
```
+----------------------+
|connection established|
+----------------------+
||
\/
+--------------------------------------+
|          server greeting             |
+--------------------------------------+
|| (1)       || (2)        || (3)
\/           ||            ||
+-----------------+    ||            ||
|Not Authenticated|    ||            ||
+-----------------+    ||            ||
|| (7)   || (4)       || …
```

✨ Track IMAP connection state

---

lib/net/imap/config.rb
lib/net/imap/config/attr_type_coercion.rb

Switching to a "Types" registry, which holds a proc for each coercion.  Also added some safeguards to ensure these procs are ractor shareable.

♻️ Refactor Config attr type coercion

---

lib/net/imap.rb

Most importantly, this documents the scenarios that need extra care to avoid memory leaks:
* Commands such as #list or #fetch can have an enormous number of responses.
* Commands such as #fetch can result in an enormous size per response.
* Long-lived connections will gradually accumulate unsolicited server responses, especially `EXISTS`, `FETCH`, and `EXPUNGE` responses.
* A buggy or untrusted server could send inappropriate responses, which could be very numerous, very large, and very rapid.

📚 Improve docs for unbounded memory use and thread safety

---

lib/net/imap.rb
test/net/imap/test_imap_response_handlers.rb

The `response_handlers` keyword argument to `Net::IMAP.new` assigns response handlers before the receiver thread is started.  This ensures every server response is handled, including the greeting.

✨ Add `response_handlers` kwarg to `Net::IMAP.new`

---

lib/net/imap/sequence_set.rb

In addition to rdoc changes, this also renames some method parameters, including for private methods.

📚 Impove SequenceSet docs

---

test/net/imap/fake_server/test_helper.rb

These are only ignored by the FakeServer thread, when the client disconnects without logging out correctly.  Some tests intentionally trigger these errors.  In other tests, it's merely distracting to see the fake server's errors rather than the client's errors.

✅ Ignore more IO errors in some FakeServer tests

---

lib/net/imap.rb

IMO, this refactoring makes `Net::IMAP#get_response` much easier to understand.
Which will be useful, because I'm about to complicate it.  😉
Details in each commit.

♻️  Refactor `Net::IMAP#get_response` (internal)

---

lib/net/imap.rb
lib/net/imap/config.rb

* Document that `open_timeout` is also used for establishing a TLS connection.
* Update rdoc for methods that delegate to `#config`: link to Config rdoc and treat them as if they were attributes.

📚 Doc improvements for open_timeout, etc

---

test/lib/helper.rb
test/net/imap/fake_server/command_reader.rb
test/net/imap/fake_server/command_router.rb
test/net/imap/fake_server/connection.rb
test/net/imap/fake_server/socket.rb
test/net/imap/fake_server/test_helper.rb

Backports the following:
* #414 
* #415 
* #421 
* `assert_pattern` from minitest (originally in #333)

✅ Backport various test improvements to v0.4

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/sequence_set.rb

Backports the following PRs to v0.4:
* #418 
* #420 
* documentation only from #416 
* #424

📚 Backport documentation to v0.4

---

lib/net/imap.rb
test/net/imap/test_imap_response_handlers.rb

Backports #419 to `v0.4-stable` (with ruby 2.7 compatibility).

✨ Add `response_handlers` kwarg to `Net::IMAP.new` (backport #419 to 0.4)

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

Updates `Config.version_defaults` to use `Rational` internally, with aliases for `Float`.
Adds a `default_proc` to `Config.version_defaults` to enable more flexible lookups.  For example, we can now use something like `Config["0.4.11"]` (I do _not_ intend to store version defaults for `x.y.z` releases).  I had to add a special-case for zero, to avoid `Config["missing"] == Config[0r]`
Fixes #428.

♻️ Rational config versions

---

lib/net/imap/config.rb
test/net/imap/test_config.rb

Backports #429 to `v0.4-stable`

♻️ Rational config version (backport #429 to v0.4)

---

lib/net/imap.rb

Backports #422 to `0.4-stable`

♻️ Refactor `get_response` (backports #422 to 0.4)

---

lib/net/imap/sequence_set.rb
test/net/imap/fixtures/response_parser/esearch_responses.yml
test/net/imap/fixtures/response_parser/rfc7162_condstore_qresync_responses.yml
test/net/imap/fixtures/response_parser/rfc9394_partial.yml
test/net/imap/fixtures/response_parser/status_responses.yml

We can perfectly reconstruct the SequenceSet from the string.  The string is the canonical IMAP representation.  And, even if the tuples representation uses less memory, the string representation will always be more compact than the naive YAML serialization of the tuples.
So only serialize the string.

✨ Customize SequenceSet YAML serialization

---

lib/net/imap.rb
lib/net/imap/response_reader.rb
test/net/imap/test_response_reader.rb

It's nice to extract a little bit of the complexity from the core `Net::IMAP` class.  But my primary motivation was so that I could directly test this code quickly and in isolation from needing to simulate a full IMAP connection.
Note that, because it wraps `@sock`, the ResponseReader _must_ be recreated (or updated) when `@sock` is replaced for TLS (or, in the future, for the `COMPRESS` extension).

♻️ Extract ResponseReader from `get_response`

---

lib/net/imap/response_reader.rb
test/net/imap/test_response_reader.rb

Save `@buff` and `@literal_size` in ivars rather locals.  This avoids the need to pass them to every method that uses them. That's not a big deal now, but it simplifies the next few changes.
Also added a missing test for empty literals: `"{0}\r\n"`.

♻️ Refactor ResponseReader

---

lib/net/imap/config.rb
lib/net/imap/config/attr_type_coercion.rb
lib/net/imap/response_reader.rb
test/net/imap/test_response_reader.rb

Backports the following to `v0.4-stable`
* #417 
* #435

♻️ Refactoring (backports)

---

lib/net/imap.rb

Backports the following to `v0.3-stable`:
* #418 
* Only the documentation from #416

📚 Docs: receiver thread, server responses, connection state

---

lib/net/imap.rb
test/net/imap/test_imap_response_handlers.rb

Backports #419 (with backport fixes from #427) to `v0.3-stable`.

✨ Backport `response_handlers`option to `new` 

---

lib/net/imap.rb
lib/net/imap/response_reader.rb
test/net/imap/test_response_reader.rb

Backports the following to `v0.3-stable`:
* #422 
* #433
includes backport fixes from #434)
* #435

♻️ Backport `ResponseReader`to v0.3 

---

.github/workflows/test.yml

In prep for the final 0.2.x release, I want to make sure we're testing against all relevant ruby versions.

✅ Add modern ruby versions to CI

---

lib/net/imap.rb
test/net/imap/test_imap_response_handlers.rb

Backports #419 to `v0.2-stable` (including compatibility fixes from #427 and #438).

✨ Add `response_handlers` option to `new` (backport)

---

lib/net/imap.rb
lib/net/imap/response_reader.rb
test/net/imap/test_response_reader.rb

Backports the following to `v0.2-stable`:
* #422 
* #433
* #434
* #435 
* #439

♻️ Backport `ResponseReader` to v0.2

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/config/attr_type_coercion.rb
lib/net/imap/errors.rb
lib/net/imap/response_reader.rb
test/net/imap/test_config.rb
test/net/imap/test_errors.rb
test/net/imap/test_imap_max_response_size.rb
test/net/imap/test_response_reader.rb

Add `Net::IMAP::Config#max_response_size`, with a _very_ high default value of 512MiB.  Use `#max_response_size` to impose a limit on incoming server responses as they are being read.  _This is especially important for untrusted servers._
Socket reads are limited to the maximum remaining bytes for the current response: `max_response_size` minus the bytes that have already been read.  When the limit is reached, or reading a `literal` _would_ go over the limit, `ResponseTooLargeError` is raised and the connection is closed.
Though it would be useful to also have limits based on response type and what commands are currently running, that's out of scope for now.
_Please note:_ this only limits the size per response.  It does _not_ limit how many unhandled responses may be stored on the …

✨ Limit `max_response_size`

---

lib/net/imap.rb
lib/net/imap/config.rb
lib/net/imap/config/attr_type_coercion.rb
lib/net/imap/errors.rb
lib/net/imap/response_reader.rb
test/net/imap/test_config.rb
test/net/imap/test_errors.rb
test/net/imap/test_imap_max_response_size.rb
test/net/imap/test_response_reader.rb

Backports #444 to `v0.4-stable`

✨ Limit max_response_size (backport 0.4)

---

lib/net/imap.rb
lib/net/imap/errors.rb
lib/net/imap/response_reader.rb
test/net/imap/test_errors.rb
test/net/imap/test_imap_max_response_size.rb
test/net/imap/test_response_reader.rb

Backports #444 to `v0.3-stable`

✨ Limit max_response_size (backport 0.3)

---

lib/net/imap.rb
lib/net/imap/errors.rb
lib/net/imap/response_reader.rb
test/net/imap/test_errors.rb
test/net/imap/test_imap_max_response_size.rb
test/net/imap/test_response_reader.rb

Backports #444 to `v0.2-stable`.

✨ Limit max_response_size (backport 0.2)

---

lib/net/imap/config/attr_type_coercion.rb

This is the same code I used in the `v0.4-stable` backport.  I didn't use it in the main branch because the minimum ruby version is 3.1.  But that breaks when JRuby and TruffleRuby try to `require "net/imap"`.
Fixes #452.

🐛 Check for Ractor (for JRuby, TruffleRuby)

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

The bug was that exclusive ranges ending in zero would be converted to end on `-1`, which would be interpreted as the last value in the range.

🐛 Fix `SequenceSet#slice` with range `(start...0)`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

This maybe isn't actually documented very well (or at all...?) but most SequenceSet transform methods return a frozen result when `self` is frozen and a mutable result when `self` is mutable.  Except `limit` which always returns a frozen result.  And (before this commit) `slice`, which inconsistently returned with matching frozen status when the result wasn't empty, but always returned a frozen set when the result _was_ empty.
(Adding these tests exposed a _much_ more significant bug: `SequenceSet#xor` mutates the receiver: #457.)

🐛 Fix inconsistently frozen SequenceSet#[] result

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

`set ^ other` and `set.xor other` are supposed to be safe transforms. But, unfortunately, they modified the receiver if it wasn't frozen, and crashed when it was!
The fix is trivial: convert `self` to `dup`.

🐛 `SequenceSet#xor` should not modify `self`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

The goal is for `#[]` (aliased as `#slice`) to behave similarly to `Array#[]`/`Array#slice`.  When `Array#slice` has a length or range that extends beyond the end of the array, they simply return everything up to the end.

🐛 Fix `SequenceSet#slice` when length > result size

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Backports the following bugfixes to `v0.4-stable`:
* #456 
* #457 
* #458 
* #459

🐛 Backport v0.4 SequenceSet bugfixes

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

When `count` is given to either of these methods, a new `SequenceSet` is returned, containing only the last `count` numbers.  An empty `SequenceSet` is returned when `self` is empty.
The goal is for these to behave similarly to `Array#min`/`#max` when they are given a count.

✨ Add `SequenceSet#min(count)` and `#max(count)`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

These are just sugar over `set - (..num)` and `set - (num..)`.  They are added because they can sometimes make the code much easier to read than doing set algebra with `-` or `&`.

✨ Add `SequenceSet#above` and `SequenceSet#below`

---

test/net/imap/test_sequence_set.rb

I almost accidentally committed a big bug for `#xor`.  I'm not sure how `#xor` escaped testing before now, but yikes!  I decided to take that opportunity to simply add some randomized tests on all of the set operators, based on set identities that should always hold true.
Later, these can also be used as a starting point for microbenchmarks and profiling of `SequenceSet`.

✅ Test `SequenceSet#xor` and fuzz test all set operations

---

lib/net/imap/sequence_set.rb

* Links back to "Ordered and Normalized Sets".
* Small updates to `*` description.
* Small updates to `min`, `max`, `minmax` summary.
* Added more "related" links.
* Added more "Set identities" sections to set operators.

📚 Various `SequenceSet` rdoc improvements

---

rakelib/string_prep_tables_generator.rb

Ruby 3.4 changed its `Hash#inspect` representation (for the better). So, every time I run rake (after switching to a branch that updates mtimes on related files), this file is converted to the ruby 3.4+ format.
This commit normalizes the output.  It uses the older format simply to keep the diff small.  Next time we update the stringprep code, we can switch to the ruby 3.4+ format.

♻️ Generate same stringprep tables with ruby 3.4

---

lib/net/imap/sequence_set.rb

Short-circuit frozen SequenceSet modifications for two reasons:
* Skip coercing inputs or calling (relatively expensive) query methods.
* Normalize the output for JRuby, which doesn't appear to use `#inspect` for its built-in frozen error (see #454).

✅ Short-circuit frozen SequenceSet modifications

---

test/net/imap/regexp_collector.rb
test/net/imap/test_regexps.rb

We'll attempt to load these tests for all ruby engines, but we'll catch failures and mark them as pending.
On @eregon's suggestion, this also prints out regexp.inspect when it fails.

✅ Update Regexp.linear_time? tests for non-CRuby

---

test/net/imap/test_deprecated_client_options.rb
test/net/imap/test_fetch_data.rb
test/net/imap/test_response_reader.rb

Splits up `ResponseReader` tests and UIDFetchData into more fine-grained tests.  Different parts of these test pass or fail on TruffleRuby or JRuby, so splitting them off into their own tests lets us mark only specific bits as pending or omitted.
The DeprecatedClientOptions tests weren't even using the correct port for the fake server, and weren't supposed to be capable of connecting anyway, so there is reason to start the server up at all.  Also, we have issues with reliably shutting the server down after an error, for both TruffleRuby and JRuby.
(See #470.)

✅ Update ResponseReader, UIDFetchData, DeprecatedClientOptions tests

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

* Bad `#include?` examples
* Fixed by #479
* Bad `:call-seq:` for `#min`/`#max`/`#minmax`
* Bad rdoc links for "Ordered and Normalized sets"
* Bad documentation of input coercion for many methods.  These hadn't been updated since the behavior changed to stop allowing any duck-typed enumerable as an input.
* Changed by (b01d864), #319.
* First release with the updated behavior was `v0.5.0`.

📚🐛 Fix Sequence documentation errors

---

.github/workflows/test.yml

This reverts commit c8f55e8a2246d4907712752f7e915f8f616bf633 (#472).
Everything seems to be passing now, so hopefully it'll stay that way. 🤞

⏪ Revert #472 (✅ CI: Mark ruby head on windows as "experimental")

---

lib/net/imap/sequence_set.rb

This is a continuation of some of the fixes in #480.

📚🐛 Fix doc & error msg for SequenceSet coersion

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

This updates `SequenceSet[]` so a frozen result from `input.to_sequence_set` is returned directly, not duplicated.
It is also updated to delegate to `SequenceSet.try_convert`.

♻️ Avoid unnecessary allocation in `SequenceSet[]`

---

lib/net/imap.rb

While attempting to get the tests running under JRuby, `#disconnect` would sometimes deadlock.  So, although I haven't seen that problem elsewhere _and_ JRuby is still failing tests with another threading issue, this  (and #494) did get most tests passing _for me_ (but not in CI).
This updates `#disconnect` so that the socket is shutdown and closed before joining the receiver thread and before waiting for the lock to change `connection_state` (It will still _attempt_ to change `connection_state` before closing the socket, but it won't wait if the lock isn't available).

🧵 Close socket in `#disconnect` before waiting for lock & thread join

---

lib/net/imap/sequence_set.rb

The rdoc misleadingly said that a SequenceSet's string cannot be set to the empty string.  While it is true that `SequenceSet#string` never returns an empty string, `#string=` _can_ be called with an empty string... it behaves the same as setting it to `nil`.

📚🐛 Fix mistake in `SequenceSet#string=` rdoc

---

lib/net/imap/sequence_set.rb

This should be converted to `TypeError`, but I'll hold off on merging that change until `v0.6.0`.

🥅 Improve ArgumentError in `SequenceSet#string=`

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

Similarly to how `#inspect` already outputs frozen sets as valid ruby to recreate an identical set with `Net::IMAP::SequenceSet[str]`, this does that for mutuble sets too using `Net::IMAP::SequenceSet(str)`.

🔎 Update `SequenceSet#inspect` format to `Net::IMAP::SequenceSet(str)`

---

benchmarks/seqset-memsize.rb
benchmarks/sequence_set-and.yml
benchmarks/sequence_set-new.yml
benchmarks/sequence_set-normalize.yml
benchmarks/sequence_set-not.yml
benchmarks/sequence_set-ops.yml
benchmarks/sequence_set-predicates.yml
benchmarks/sequence_set-slice.yml
benchmarks/sequence_set-xor.yml

This adds:
* ruby script for measuring memory usage with `ObjectSpace.memsize_of`
* benchmark-driver scripts for:
* `.new` (indirectly via `::[]`)
* `#slice` (aka `#[]`)
* various set ops: `&`, `|`, `-`, `^`, `~`
* various set predicates: `#intersect?`, `#disjoint?`, `#cover?`
* benchmark-driver scripts for alternate implementations of:
* AND — `#&` and `#intersect!`
* NOT — `#~` and `#complement!`
* XOR — `#^` and `#xor!`
🚧 TODO in future PRs:
* Add benchmark for `#find_index`
* Add benchmark for `#ordered_at`
* Add benchmark for `#find_ordered_index`
* Replace methods with faster implementations

📉 Add SequenceSet benchmarks

---

benchmarks/sequence_set-normalize.yml

I'd forgotten that `SequenceSet#append` partially normalizes its input (no sorting nor coalescing, but each entry is converted to normal form). But the benchmark was specifically meant to test the non-normal forms.

📉 Fix benchmark data for SequenceSet#normalize

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

When using SequenceSet to store mailbox state for mailboxes with many millions of messages, the last thing you want to do is accidentally generate a string and output that!
So this establishes a maximum number of entries to output as an inspect string, currently 512.  Above that number, we output only a much smaller number of entries from the head and tail, currently 16 from each end.  When the sequence set has an internal denormalized string, we use regexps to grab the first and last groups of entries from that.
```ruby
Net::IMAP::SequenceSet(((1..5000) % 2).to_a).inspect
#=> #<Net::IMAP::SequenceSet 2500 entries "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,...(2468 entries omitted)...,4969,4971,4973,4975,4977,4979,4981,4983,4985,4987,4989,4991,4993,4995,4997,4999">
```
At first, I used a …

⚡🔎 Abridged SequenceSet#inspect output

---

Gemfile
benchmarks/sequence_set-new.yml
benchmarks/sequence_set-normalize.yml
benchmarks/sequence_set-predicates.yml
benchmarks/sequence_set-slice.yml
test/lib/helper.rb
test/lib/profiling_helper.rb
test/net/imap/test_sequence_set.rb

Export `NET_IMAP_PROFILE=1` before running tests or benchmarks.  Profiling data will be written to `~/.cache/net-imap`, or export `NET_IMAP_PROFILE_OUTDIR=dirname` to configure the output dir.
Some of the benchmarks have a second barrier to profiling: setting `$allowed_to_profile = true`.  This way we don't accidentally profile older releases of the gem.
Export `SIMPLECOV_DISABLE=1` to disable simplecov.
Export `PROFILE_ALLOCATIONS=1` to print GC object allocation stats (tests only).

⚡ Add vernier profiler for SequenceSet tests and benchmarks

---

lib/net/imap/flags.rb

🐛 Fix spelling of `\Remote` mailbox attr constant

---

lib/net/imap/sequence_set.rb
test/net/imap/test_sequence_set.rb

If `obj.to_sequence_set` returns `nil`, then `SequenceSet.try_convert` should return `nil`.  This is consistent with how ruby's built-in `try_convert` methods work.

✨ Allow `obj.to_sequence_set => nil` in try_convert

---

lib/net/imap/vanished_data.rb
test/net/imap/test_vanished_data.rb

This isn't a valid server response.  But it's useful as a null object.  It will be used when `Net::IMAP#uid_fetch` is called with `vanished: true` but the server returns nothing.

♻️ Allow `VanishedData#uids` to be `SequenceSet.empty`

---

lib/net/imap.rb
test/net/imap/test_imap_fetch.rb

The `PARTIAL` fetch modifier is only valid for `UID FETCH`.  This raises an `ArgumentError`, rather than send an invalid command to the server.

🥅 Raise `ArgumentError` for `#fetch` with `partial`

---

.github/workflows/test.yml
Gemfile
test/lib/helper.rb
test/net/imap/test_connection_state.rb
test/net/imap/test_data_lite.rb

No application code is updated by this PR; only the test suite.  3 tests are marked pending, but the rest are all passing.  So, with a few caveats, it looks like TruffleRuby _mostly_ works.  This doesn't mean that TruffleRuby is "officially supported", but it _does_ mean that we'll try not to merge PRs that break tests that aren't broken.
Partially replaces #454.

✅ Add TruffleRuby to CI
